Doxygen: /home/runner/work/doxygen/doxygen/src/message.cpp File Reference
message.cpp File Reference
#include <stdio.h>
#include "config.h"
#include "debug.h"
#include "portable.h"
#include "message.h"
#include "doxygen.h"
#include <mutex>
#include <atomic>
Functions
void initWarningFormat ()
void msg (const char *fmt,...)
static void format_warn (const QCString &file, int line, const QCString &text)
static void handle_warn_as_error ()
static void do_warn (bool enabled, const QCString &file, int line, const char *prefix, const char *fmt, va_list args)
QCString warn_line (const QCString &file, int line)
void warn (const QCString &file, int line, const char *fmt,...)
void va_warn (const QCString &file, int line, const char *fmt, va_list args)
void warn_simple (const QCString &file, int line, const char *text)
void warn_undoc (const QCString &file, int line, const char *fmt,...)
void warn_incomplete_doc (const QCString &file, int line, const char *fmt,...)
void warn_doc_error (const QCString &file, int line, const char *fmt,...)
void warn_uncond (const char *fmt,...)
void err (const char *fmt,...)
void err_full (const QCString &file, int line, const char *fmt,...)
void term (const char *fmt,...)
void warn_flush ()
void finishWarnExit ()
Variables
static QCString g_warnFormat
static QCString g_warnLineFormat
static const char * g_warningStr = "warning: "
static const char * g_errorStr = "error: "
static FILE * g_warnFile = stderr
static WARN_AS_ERROR_t g_warnBehavior = WARN_AS_ERROR_t::NO
static QCString g_warnlogFile
static bool g_warnlogTemp = false
static std::atomic_bool g_warnStat = false
static std::mutex g_mutex
Function Documentation
do_warn()
static void do_warn (bool enabled, const QCString & file, int line, const char * prefix, const char * fmt, va_list args) static
Definition at line 146 of file message.cpp.
{
  if (!enabled) return; // warning type disabled
  va_list argsCopy;
  va_copy(argsCopy, args);
  size_t l=0;
  if (prefix)
  {
    l=strlen(prefix);
  }
  // determine needed buffersize based on:
  // format + arguments
  // prefix
  // 1 position for `\0`
  size_t bufSize = vsnprintf(NULL, 0, fmt, args) + l + 1;
  QCString text(bufSize);
  if (prefix)
  {
    qstrncpy(text.rawData(),prefix,bufSize);
  }
  vsnprintf(text.rawData()+l, bufSize-l, fmt, argsCopy);
  text[static_cast<int>(bufSize)-1]='\0';
  format_warn(file,line,text);
  va_end(argsCopy);
}
References format_warn(), prefix, qstrncpy(), and QCString::rawData().
Referenced by err_full(), va_warn(), warn(), warn_doc_error(), warn_incomplete_doc(), and warn_undoc().
err()
void err (const char * fmt, ...)
Definition at line 239 of file message.cpp.
{
  va_list args;
  va_start(args, fmt);
  vfprintf(g_warnFile, (QCString(g_errorStr) + fmt).data(), args);
  va_end(args);
  handle_warn_as_error();
}
References g_errorStr, g_warnFile, and handle_warn_as_error().
Referenced by MemberDefImpl::_writeReimplements(), FileDefImpl::acquireFileVersion(), DefinitionImpl::addInnerCompound(), adjustBoolSetting(), adjustColorStyleSetting(), adjustConfiguration(), adjustStringSetting(), MemberContext::Private::callerGraph(), MemberContext::Private::callGraph(), Config::checkAndCorrect(), checkFileName(), checkList(), checkPngResult(), classInheritedProtectionLevel(), ClassContext::Private::collaborationDiagram(), DotFilePatcher::convertMapFile(), convertMapFile(), copyExtraFiles(), copyFile(), copyLatexStyleSheet(), copyLogo(), ResourceMgr::copyResourceAs(), copyStyleSheet(), MemberList::countDecMembers(), createCroppedEPS(), createCroppedPDF(), createDVIFile(), createEPSbboxFile(), PerlModGenerator::createOutputDir(), createOutputDirectory(), PerlModGenerator::createOutputFile(), createPNG(), createPostscriptFile(), HtmlHelp::Private::createProjectFile(), DotManager::createRunner(), createSVG(), FlowChart::createSVG(), createSVGFromPDF(), createSVGFromPDFviaInkscape(), RTFGenerator::decIndentLevel(), NamespaceLinkedRefMap::declVisible(), DirContext::Private::dirGraph(), elemIsVisible(), Htags::execute(), extractBoundingBox(), fileToString(), DocParser::findAndCopyImage(), FlowChart::findLabel(), finishWarnExit(), generateDEF(), generateFormula(), generateLink(), generateOutput(), CitationManager::generatePage(), generateSqlite3(), generateTemplateFiles(), generateXML(), generateXMLForClass(), generateXMLForConcept(), generateXMLForDir(), generateXMLForFile(), generateXMLForGroup(), generateXMLForNamespace(), generateXMLForPage(), FilterCache::getFileContentsPipe(), ModuleContext::Private::groupGraph(), TranslateContext::Private::handleCollaborationDiagramFor(), MemberContext::Private::handleDetailsVisibleFor(), TranslateContext::Private::handleDirDependencyGraphFor(), TranslateContext::Private::handleGeneratedAt(), TranslateContext::Private::handleImplementedBy(), TranslateContext::Private::handleIncludeDependencyGraph(), TranslateContext::Private::handleInheritanceDiagramFor(), TranslateContext::Private::handleInheritedByList(), TranslateContext::Private::handleInheritsList(), MemberContext::Private::handleNameWithContextFor(), TranslateContext::Private::handleReimplementedBy(), DocPara::handleShowDate(), TranslateContext::Private::handleSourceRefBys(), TranslateContext::Private::handleSourceRefs(), TranslateContext::Private::handleWriteList(), hasNonReferenceSuperClassRec(), LatexDocVisitor::incIndentLevel(), RTFDocVisitor::incIndentLevel(), RTFGenerator::incIndentLevel(), FileContext::Private::includedByGraph(), FileContext::Private::includeGraph(), ClassContext::Private::inheritanceDiagram(), RTFGenerator::init(), initWarningFormat(), CitationManager::insertCrossReferencesForBibFile(), GroupDefImpl::insertMember(), FileDefImpl::insertMember(), NamespaceDefImpl::insertMember(), ClassDefImpl::internalInsertMember(), ClassDefImpl::isBaseClass(), ClassDefImpl::isSubClass(), VhdlDocGen::isSubClass(), TemplateEngine::Private::loadByName(), loadExtensions(), Htags::loadFilemap(), loadStylesheet(), TemplateNodeCreator< T >::mkpath(), DocbookDocVisitor::operator()(), HtmlDocVisitor::operator()(), LatexDocVisitor::operator()(), ManDocVisitor::operator()(), PerlModDocVisitor::operator()(), RTFDocVisitor::operator()(), XmlDocVisitor::operator()(), PrintDocVisitor::operator()(), PerlModDocVisitor::operator()(), PerlModDocVisitor::operator()(), DocbookDocVisitor::operator()(), HtmlDocVisitor::operator()(), LatexDocVisitor::operator()(), PerlModDocVisitor::operator()(), RTFDocVisitor::operator()(), TextDocVisitor::operator()(), XmlDocVisitor::operator()(), DocbookDocVisitor::operator()(), HtmlDocVisitor::operator()(), LatexDocVisitor::operator()(), RTFDocVisitor::operator()(), DocInclude::parse(), parseCode(), parseCode(), parseDoc(), parseInput(), DotGraph::prepareDotFile(), preProcessFile(), RTFGenerator::preProcessFileInplace(), DotRunner::readBoundingBox(), readConfiguration(), readInputFile(), readTagFile(), MemberContext::Private::referencedByRelation(), MemberContext::Private::referencesRelation(), GroupDefImpl::removeMember(), resetPDFSize(), DotFilePatcher::run(), runHtmlHelpCompiler(), runQHelpGenerator(), StyleData::setStyle(), SysTimeKeeper::stop(), testRTFOutput(), transcodeCharacterStringToUTF8(), updateEPSBoundingBox(), updateLanguageMapping(), SearchIndexExternal::write(), ResourceMgr::writeCategory(), writeCombineScript(), writeDefaultLayoutFile(), FileDefImpl::writeDetailedDescription(), writeDiaGraphFromFile(), ConceptDefImpl::writeDocumentation(), DirDefImpl::writeDocumentation(), FileDefImpl::writeDocumentation(), GroupDefImpl::writeDocumentation(), NamespaceDefImpl::writeDocumentation(), MemberList::writeDocumentation(), ClassDefImpl::writeDocumentationContents(), HtmlGenerator::writeExternalSearchPage(), ClassDiagram::writeFigure(), FlowChart::writeFlowChart(), writeJavaScriptSearchIndex(), VhdlDocGen::writeOverview(), MemberList::writePlainDeclarations(), HtmlGenerator::writeSearchPage(), DefinitionImpl::writeSourceDef(), HtmlGenerator::writeStyleInfo(), and writeTagFile().
err_full()
void err_full (const QCString & file, int line, const char * fmt, ...)
Definition at line 248 of file message.cpp.
{
  va_list args;
  va_start(args, fmt);
  do_warn(TRUE, file, line, g_errorStr, fmt, args);
  va_end(args);
}
References do_warn(), g_errorStr, and TRUE.
Referenced by NamespaceDefImpl::compoundTypeString(), getMscImageMapFromFile(), DotRunner::run(), runPlantumlContent(), writeDiaGraphFromFile(), and writeMscGraphFromFile().
finishWarnExit()
void finishWarnExit ()
Definition at line 282 of file message.cpp.
{
  if (g_warnBehavior == WARN_AS_ERROR_t::FAIL_ON_WARNINGS_PRINT && g_warnlogFile != "-")
  {
    Portable::fclose(g_warnFile);
  }
  if (g_warnStat && g_warnBehavior == WARN_AS_ERROR_t::FAIL_ON_WARNINGS_PRINT && g_warnlogFile != "-")
  {
    std::ifstream warnFile = Portable::openInputStream(g_warnlogFile);
    if (!warnFile.is_open())
    {
      g_warnFile = stderr;
      err("Cannot open warnings file '%s' for reading\n",g_warnlogFile.data());
    }
    else
    {
      std::string line;
      while (getline(warnFile,line))
      {
        fprintf(stderr,"%s\n",line.c_str());
      }
      warnFile.close();
    }
  }
  if (g_warnlogTemp) Portable::unlink(g_warnlogFile);
  if (g_warnStat && (g_warnBehavior == WARN_AS_ERROR_t::FAIL_ON_WARNINGS ||
                     g_warnBehavior == WARN_AS_ERROR_t::FAIL_ON_WARNINGS_PRINT))
  {
    Doxygen::terminating=true;
    exit(1);
  }
}
References QCString::data(), err(), Portable::fclose(), g_warnBehavior, g_warnFile, g_warnlogFile, g_warnlogTemp, g_warnStat, Portable::openInputStream(), Doxygen::terminating, and Portable::unlink().
Referenced by generateOutput().
format_warn()
static void format_warn (const QCString & file, int line, const QCString & text) static
Definition at line 91 of file message.cpp.
{
  QCString fileSubst = file.isEmpty() ? "<unknown>" : file;
  QCString lineSubst; lineSubst.setNum(line);
  QCString textSubst = text;
  QCString versionSubst;
  // substitute markers by actual values
  QCString msgText =
      substitute(
        substitute(
          substitute(
            substitute(
              g_warnFormat,
              "$file",fileSubst
            ),
            "$line",lineSubst
          ),
          "$version",versionSubst
        ),
        "$text",textSubst
      );
  if (g_warnBehavior == WARN_AS_ERROR_t::YES)
  {
    msgText += " (warning treated as error, aborting now)";
  }
  msgText += '\n';
  {
    std::unique_lock<std::mutex> lock(g_mutex);
    // print resulting message
    fwrite(msgText.data(),1,msgText.length(),g_warnFile);
  }
  if (g_warnBehavior == WARN_AS_ERROR_t::YES)
  {
    Doxygen::terminating=true;
    exit(1);
  }
  g_warnStat = true;
}
References QCString::data(), g_mutex, g_warnBehavior, g_warnFile, g_warnFormat, g_warnStat, QCString::isEmpty(), QCString::length(), QCString::setNum(), substitute(), and Doxygen::terminating.
Referenced by do_warn(), and warn_simple().
handle_warn_as_error()
static void handle_warn_as_error () static
Definition at line 131 of file message.cpp.
{
  if (g_warnBehavior == WARN_AS_ERROR_t::YES)
  {
    {
      std::unique_lock<std::mutex> lock(g_mutex);
      QCString msgText = " (warning treated as error, aborting now)\n";
      fwrite(msgText.data(),1,msgText.length(),g_warnFile);
    }
    Doxygen::terminating=true;
    exit(1);
  }
  g_warnStat = true;
}
References QCString::data(), g_mutex, g_warnBehavior, g_warnFile, g_warnStat, QCString::length(), and Doxygen::terminating.
Referenced by err(), and warn_uncond().
initWarningFormat()
void initWarningFormat ()
Definition at line 38 of file message.cpp.
{
  g_warnFormat = Config_getString(WARN_FORMAT);
  g_warnLineFormat = Config_getString(WARN_LINE_FORMAT);
  g_warnBehavior = Config_getEnum(WARN_AS_ERROR);
  g_warnlogFile = Config_getString(WARN_LOGFILE);
  if (g_warnlogFile.isEmpty() && g_warnBehavior == WARN_AS_ERROR_t::FAIL_ON_WARNINGS_PRINT)
  {
    uint32_t pid = Portable::pid();
    g_warnlogFile.sprintf("doxygen_warnings_temp_%d.tmp",pid);
    g_warnlogTemp = true;
  }
  if (!g_warnlogFile.isEmpty())
  {
    if (g_warnlogFile == "-")
    {
      g_warnFile = stdout;
    }
    else if (!(g_warnFile = Portable::fopen(g_warnlogFile,"w")))
    {
      // point it to something valid, because warn() relies on it
      g_warnFile = stderr;
      err("Cannot open '%s' for writing, redirecting 'WARN_LOGFILE' output to 'stderr'\n",g_warnlogFile.data());
    }
  }
  else
  {
    g_warnFile = stderr;
  }
  if (g_warnBehavior != WARN_AS_ERROR_t::NO)
  {
    g_warningStr = g_errorStr;
  }
}
References Config_getEnum, Config_getString, QCString::data(), err(), Portable::fopen(), g_errorStr, g_warnBehavior, g_warnFile, g_warnFormat, g_warningStr, g_warnLineFormat, g_warnlogFile, g_warnlogTemp, QCString::isEmpty(), Portable::pid(), and QCString::sprintf().
Referenced by checkConfiguration().
msg()
void msg (const char * fmt, ...)
Definition at line 75 of file message.cpp.
{
  if (!Config_getBool(QUIET))
  {
    std::unique_lock<std::mutex> lock(g_mutex);
    if (Debug::isFlagSet(Debug::Time))
    {
      printf("%.3f sec: ",(static_cast<double>(Debug::elapsedTime())));
    }
    va_list args;
    va_start(args, fmt);
    vfprintf(stdout, fmt, args);
    va_end(args);
  }
}
References Config_getBool, Debug::elapsedTime(), g_mutex, Debug::isFlagSet(), and Debug::Time.
Referenced by MemberDefImpl::_writeCallerGraph(), MemberDefImpl::_writeCallGraph(), FileDefImpl::acquireFileVersion(), adjustConfiguration(), Statistics::begin(), RTFGenerator::beginRTFDocument(), checkAndUpdatePath(), devUsage(), LayoutParser::error(), exitDoxygen(), generateConceptDocs(), generateConfigFile(), generateDocsForClassList(), generateExampleDocs(), generateFileDocs(), generateFileSources(), generateFormula(), generateNamespaceClassDocs(), generateNamespaceConceptDocs(), generateNamespaceDocs(), generateOutput(), generatePageDocs(), generateXML(), generateXMLForClass(), LayoutDocManager::init(), FormulaManager::initFromRepository(), loadExtensions(), loadStylesheet(), XMLParser::parse(), LayoutDocManager::parse(), parseFile(), parseFilesMultiThreading(), parseInput(), parseMain(), parseMain(), parseMain(), parseMain(), parseTagFile(), Statistics::print(), Debug::printFlags(), printNavTree(), processData(), readConfiguration(), readDir(), readIncludeFile(), readTagFile(), TemplateNodeExtend::render(), reportError(), DotManager::run(), runPlantumlContent(), AutoTrace::setExit(), setTranslator(), stopDoxygen(), LayoutNavEntry::url(), usage(), version(), DirDefImpl::writeDirectoryGraph(), ClassDefImpl::writeDocumentationForInnerClasses(), GroupDefImpl::writeGroupGraph(), and writeIndexHierarchyEntries().
term()
void term (const char * fmt, ...)
Definition at line 256 of file message.cpp.
{
  {
    std::unique_lock<std::mutex> lock(g_mutex);
    va_list args;
    va_start(args, fmt);
    vfprintf(g_warnFile, (QCString(g_errorStr) + fmt).data(), args);
    va_end(args);
    if (g_warnFile != stderr)
    {
      size_t l = strlen(g_errorStr);
      for (size_t i=0; i<l; i++) fprintf(g_warnFile, " ");
      fprintf(g_warnFile, "%s\n", "Exiting...");
    }
  }
  Doxygen::terminating=true;
  exit(1);
}
References g_errorStr, g_mutex, g_warnFile, and Doxygen::terminating.
Referenced by addTillEndOfString(), adjustConfiguration(), checkPageRelations(), compareDoxyfile(), computePageRelations(), createSubDirs(), generateConfigFile(), FormulaManager::generateImages(), generateOutput(), DocbookGenerator::init(), HtmlGenerator::init(), LatexGenerator::init(), ManGenerator::init(), RTFGenerator::init(), DocSets::initialize(), EclipseHelp::initialize(), HtmlHelpRecoder::initialize(), HtmlHelp::initialize(), Qhp::initialize(), DotGraph::prepareDotFile(), processUntilMatchingTerminator(), OutputGenerator::startPlainFile(), transcodeCharacterBuffer(), writeDotGraphFromFile(), writeDotImageMapFromFile(), ClassDiagram::writeFigure(), DotGfxHierarchyTable::writeGraph(), writeLatexMakefile(), and writeMakeBat().
va_warn()
void va_warn (const QCString & file, int line, const char * fmt, va_list args)
Definition at line 195 of file message.cpp.
{
  do_warn(Config_getBool(WARNINGS), file, line, g_warningStr, fmt, args);
}
References Config_getBool, do_warn(), and g_warningStr.
Referenced by TemplateContextImpl::warn(), and TemplateParser::warn().
warn()
void warn (const QCString & file, int line, const char * fmt, ...)
Definition at line 187 of file message.cpp.
{
  va_list args;
  va_start(args, fmt);
  do_warn(Config_getBool(WARNINGS), file, line, g_warningStr, fmt, args);
  va_end(args);
}
References Config_getBool, do_warn(), and g_warningStr.
Referenced by addAnchor(), addGroupToGroups(), addIncludeFile(), addMemberDocs(), addMemberToGroups(), addRelatedPage(), addSection(), addXRefItem(), buildExampleList(), buildFileList(), buildGroupListFiltered(), checkFormula(), DocGroup::close(), convertCppComments(), decrLevel(), endCondSection(), endCondSection(), DocGroup::enterCompound(), LayoutParser::error(), Markdown::extractTitleId(), findClassRelation(), findDefineDocumentation(), findDirDocumentation(), findEnumDocumentation(), findGlobalMember(), findMainPage(), findMember(), getConvertLatexMacro(), ExpressionParser::getNextToken(), MemberDefImpl::getOutputFileBase(), DocPara::handleCommand(), handleElse(), handleElseIf(), handleEndIf(), handleEndParBlock(), handleExample(), handleFileInfo(), handleMemberOf(), vhdl::parser::VhdlErrorHandler::handleOtherError(), handleParBlock(), vhdl::parser::VhdlErrorHandler::handleParseError(), handleRelated(), handleRelatedAlso(), handleSubpage(), handleToc(), vhdl::parser::VhdlErrorHandler::handleUnexpectedToken(), ClassDefImpl::internalInsertMember(), DocGroup::leaveFile(), vhdl::parser::VhdlTokenManagerErrorHandler::lexicalError(), vhdl::parser::VhdlTokenManagerErrorHandler::lexicalError(), loadExtensions(), loadStylesheet(), otherCaseDone(), CondParser::parse(), CommentScanner::parseCommentBlock(), parseMain(), ExpressionParser::parseNotExpression(), ExpressionParser::parsePrimaryExpression(), parsePrototype(), parsePrototype(), pop_state(), pop_state(), pop_state(), TemplateEngine::Private::printIncludeContext(), Preprocessor::processFile(), processSection(), readIncludeFile(), resolveClassNestingRelations(), LayoutParser::startElement(), LayoutParser::startNavEntry(), subrHandleCommentBlock(), TemplateLexer::tokenize(), MemberDefImpl::virtualness(), MemberDefImpl::warnIfUndocumented(), writeDirTreeNode(), writeExceptionListImpl(), and writeGroupTreeNode().
warn_doc_error()
void warn_doc_error (const QCString & file, int line, const char * fmt, ...)
Definition at line 222 of file message.cpp.
{
  va_list args;
  va_start(args, fmt);
  do_warn(Config_getBool(WARN_IF_DOC_ERROR), file, line, g_warningStr, fmt, args);
  va_end(args);
}
References Config_getBool, do_warn(), and g_warningStr.
Referenced by DocParser::checkArgumentName(), DocParser::checkRetvalName(), DocParser::checkUnOrMultipleDocumentedParams(), DocParser::defaultHandleTitleAndSize(), DocParser::defaultHandleToken(), DocAnchor::DocAnchor(), DocCite::DocCite(), DocEmoji::DocEmoji(), DocFormula::DocFormula(), DocHtmlCaption::DocHtmlCaption(), DocLink::DocLink(), DocRef::DocRef(), DocParser::errorHandleDefaultToken(), DocParser::findAndCopyImage(), DocParser::handleAHref(), DocParser::handleAnchor(), DocPara::handleCite(), DocPara::handleCommand(), DocPara::handleEmoji(), DocPara::handleFile(), DocPara::handleHtmlEndTag(), DocPara::handleHtmlStartTag(), DocPara::handleIFile(), DocPara::handleILine(), DocParser::handleImage(), DocParser::handleImg(), DocPara::handleInclude(), DocPara::handleIncludeOperator(), DocParser::handleInternalRef(), DocPara::handleLink(), DocParser::handleLinkedWord(), DocPara::handleRef(), DocPara::handleSection(), DocPara::handleShowDate(), DocPara::handleStartCode(), DocParser::handleStyleArgument(), DocParser::handleStyleLeave(), DocParser::handleUnclosedStyleCommands(), DocInclude::parse(), DocIncOperator::parse(), DocIndexEntry::parse(), DocDotFile::parse(), DocMscFile::parse(), DocDiaFile::parse(), DocHRef::parse(), DocHtmlHeader::parse(), DocHtmlDescTitle::parse(), DocHtmlDescList::parse(), DocSection::parse(), DocSecRefItem::parse(), DocSecRefList::parse(), DocHtmlList::parse(), DocPara::parse(), DocHtmlCaption::parse(), DocHtmlRow::parse(), DocHtmlTable::parse(), DocText::parse(), DocRoot::parse(), DocLink::parse(), DocParamList::parse(), DocInternal::parse(), DocHtmlList::parseXml(), DocHtmlRow::parseXml(), DocParamList::parseXml(), DocParser::processCopyDoc(), DocParser::readTextFileByName(), and MemberDefImpl::warnIfUndocumentedParams().
warn_flush()
void warn_flush ()
Definition at line 275 of file message.cpp.
{
  fflush(g_warnFile);
}
References g_warnFile.
Referenced by generateOutput().
warn_incomplete_doc()
void warn_incomplete_doc (const QCString & file, int line, const char * fmt, ...)
Definition at line 214 of file message.cpp.
{
  va_list args;
  va_start(args, fmt);
  do_warn(Config_getBool(WARN_IF_INCOMPLETE_DOC), file, line, g_warningStr, fmt, args);
  va_end(args);
}
References Config_getBool, do_warn(), and g_warningStr.
Referenced by DocParser::checkUnOrMultipleDocumentedParams().
warn_line()
QCString warn_line (const QCString & file, int line)
Definition at line 175 of file message.cpp.
{
  QCString fileSubst = file.isEmpty() ? "<unknown>" : file;
  QCString lineSubst; lineSubst.setNum(line);
  return  substitute(
            substitute(
              g_warnLineFormat,
              "$file",fileSubst
            ),
            "$line",lineSubst
          );
}
References g_warnLineFormat, QCString::isEmpty(), QCString::setNum(), and substitute().
Referenced by addMemberFunction(), checkPageRelations(), computePageRelations(), and findGlobalMember().
warn_simple()
void warn_simple (const QCString & file, int line, const char * text)
Definition at line 200 of file message.cpp.
{
  if (!Config_getBool(WARNINGS)) return; // warning type disabled
  format_warn(file,line,QCString(g_warningStr) + text);
}
References Config_getBool, format_warn(), and g_warningStr.
Referenced by addMemberFunction().
warn_uncond()
void warn_uncond (const char * fmt, ...)
Definition at line 230 of file message.cpp.
{
  va_list args;
  va_start(args, fmt);
  vfprintf(g_warnFile, (QCString(g_warningStr) + fmt).data(), args);
  va_end(args);
  handle_warn_as_error();
}
References g_warnFile, g_warningStr, and handle_warn_as_error().
Referenced by MemberDefImpl::_writeCallerGraph(), MemberDefImpl::_writeCallGraph(), Config::checkAndCorrect(), computeVerifiedDotPath(), getCurrentDateTime(), getResolvedNamespace(), FormulaManager::initFromRepository(), minClassDistance(), parseInput(), readDir(), readFileOrDirectory(), searchInputFiles(), Config::updateObsolete(), HtmlEntityMapper::validate(), FileDefImpl::writeIncludedByGraph(), FileDefImpl::writeIncludeGraph(), and ClassDefImpl::writeInheritanceGraph().
warn_undoc()
void warn_undoc (const QCString & file, int line, const char * fmt, ...)
Definition at line 206 of file message.cpp.
{
  va_list args;
  va_start(args, fmt);
  do_warn(Config_getBool(WARN_IF_UNDOCUMENTED), file, line, g_warningStr, fmt, args);
  va_end(args);
}
References Config_getBool, do_warn(), and g_warningStr.
Referenced by computeClassRelations(), findMember(), and MemberDefImpl::warnIfUndocumented().
Variable Documentation
g_errorStr
const char* g_errorStr = "error: " static
Definition at line 30 of file message.cpp.
Referenced by err(), err_full(), initWarningFormat(), and term().
g_mutex
std::mutex g_mutex static
Definition at line 36 of file message.cpp.
Referenced by format_warn(), handle_warn_as_error(), msg(), and term().
g_warnBehavior
WARN_AS_ERROR_t g_warnBehavior = WARN_AS_ERROR_t::NO static
Definition at line 32 of file message.cpp.
Referenced by finishWarnExit(), format_warn(), handle_warn_as_error(), and initWarningFormat().
g_warnFile
FILE* g_warnFile = stderr static
Definition at line 31 of file message.cpp.
Referenced by err(), finishWarnExit(), format_warn(), handle_warn_as_error(), initWarningFormat(), term(), warn_flush(), and warn_uncond().
g_warnFormat
QCString g_warnFormat static
Definition at line 27 of file message.cpp.
Referenced by format_warn(), and initWarningFormat().
g_warningStr
const char* g_warningStr = "warning: " static
Definition at line 29 of file message.cpp.
Referenced by initWarningFormat(), va_warn(), warn(), warn_doc_error(), warn_incomplete_doc(), warn_simple(), warn_uncond(), and warn_undoc().
g_warnLineFormat
QCString g_warnLineFormat static
Definition at line 28 of file message.cpp.
Referenced by initWarningFormat(), and warn_line().
g_warnlogFile
QCString g_warnlogFile static
Definition at line 33 of file message.cpp.
Referenced by finishWarnExit(), and initWarningFormat().
g_warnlogTemp
bool g_warnlogTemp = false static
Definition at line 34 of file message.cpp.
Referenced by finishWarnExit(), and initWarningFormat().
g_warnStat
std::atomic_bool g_warnStat = false static
Definition at line 35 of file message.cpp.
Referenced by finishWarnExit(), format_warn(), and handle_warn_as_error().