Doxygen: /home/runner/work/doxygen/doxygen/src/classdef.h File Reference
classdef.h File Reference
#include <vector>
#include <set>
#include "containers.h"
#include "definition.h"
#include "arguments.h"
#include "membergroup.h"
Classes
struct BaseClassDef
Class that contains information about an inheritance relation.
struct TemplateInstanceDef
Class that contains information about a template instance relation.
class ClassDef
A abstract class representing of a compound symbol.
class ClassDefMutable
struct UsesClassDef
Class that contains information about a usage relation.
class UsesClassList
struct ConstraintClassDef
Class that contains information about a type constraint relations.
class ConstraintClassList
Typedefs
using BaseClassList = std::vector< BaseClassDef >
using TemplateInstanceList = std::vector< TemplateInstanceDef >
using TemplateNameMap = std::map< std::string, int >
using ClassDefSet = std::set< const ClassDef * >
Functions
ClassDefMutable * createClassDef (const QCString &fileName, int startLine, int startColumn, const QCString &name, ClassDef::CompoundType ct, const QCString &ref=QCString(), const QCString &fName=QCString(), bool isSymbol=TRUE, bool isJavaEnum=FALSE)
Factory method to create a new ClassDef object.
ClassDef * createClassDefAlias (const Definition *newScope, const ClassDef *cd)
ClassDef * toClassDef (Definition *d)
ClassDef * toClassDef (DefinitionMutable *d)
const ClassDef * toClassDef (const Definition *d)
ClassDefMutable * toClassDefMutable (Definition *d)
ClassDefMutable * toClassDefMutable (const Definition *d)
ClassDef * getClass (const QCString &key)
ClassDefMutable * getClassMutable (const QCString &key)
bool hasVisibleRoot (const BaseClassList &bcl)
bool classHasVisibleChildren (const ClassDef *cd)
bool classVisibleInIndex (const ClassDef *cd)
int minClassDistance (const ClassDef *cd, const ClassDef *bcd, int level=0)
Protection classInheritedProtectionLevel (const ClassDef *cd, const ClassDef *bcd, Protection prot=Public, int level=0)
Typedef Documentation
BaseClassList
using BaseClassList = std::vector<BaseClassDef>
Definition at line 81 of file classdef.h.
ClassDefSet
using ClassDefSet = std::set<const ClassDef*>
Definition at line 95 of file classdef.h.
TemplateInstanceList
using TemplateInstanceList = std::vector<TemplateInstanceDef>
Definition at line 91 of file classdef.h.
TemplateNameMap
using TemplateNameMap = std::map<std::string,int>
Definition at line 93 of file classdef.h.
Function Documentation
classHasVisibleChildren()
bool classHasVisibleChildren (const ClassDef * cd)
Definition at line 5044 of file classdef.cpp.
{
  BaseClassList bcl;
  if (cd->getLanguage()==SrcLangExt_VHDL) // reverse baseClass/subClass relation
  {
    if (cd->baseClasses().empty()) return FALSE;
    bcl=cd->baseClasses();
  }
  else
  {
    if (cd->subClasses().empty()) return FALSE;
    bcl=cd->subClasses();
  }
  for (const auto &bcd : bcl)
  {
    if (bcd.classDef->isVisibleInHierarchy())
    {
      return TRUE;
    }
  }
  return FALSE;
}
References ClassDef::baseClasses(), FALSE, Definition::getLanguage(), SrcLangExt_VHDL, ClassDef::subClasses(), and TRUE.
Referenced by NestingNodeContext::Private::addClasses(), writeClassTreeForList(), and writeClassTreeToOutput().
classInheritedProtectionLevel()
Protection classInheritedProtectionLevel (const ClassDef * cd, const ClassDef * bcd, Protection prot = Public, int level = 0)
Definition at line 5104 of file classdef.cpp.
{
  if (bcd->categoryOf()) // use class that is being extended in case of
    // an Objective-C category
  {
    bcd=bcd->categoryOf();
  }
  if (cd==bcd)
  {
    goto exit;
  }
  if (level==256)
  {
    err("Internal inconsistency: found class %s seem to have a recursive "
        "inheritance relation! Please send a bug report to doxygen@gmail.com\n",qPrint(cd->name()));
  }
  else if (prot!=Private)
  {
    for (const auto &bcdi : cd->baseClasses())
    {
      Protection baseProt = classInheritedProtectionLevel(bcdi.classDef,bcd,bcdi.prot,level+1);
      if (baseProt==Private)        prot=Private;
      else if (baseProt==Protected) prot=Protected;
    }
  }
exit:
  //printf("classInheritedProtectionLevel(%s,%s)=%d\n",qPrint(cd->name()),qPrint(bcd->name()),prot);
  return prot;
}
References ClassDef::baseClasses(), ClassDef::categoryOf(), classInheritedProtectionLevel(), err(), Definition::name(), Private, Protected, and qPrint().
Referenced by classInheritedProtectionLevel().
classVisibleInIndex()
bool classVisibleInIndex (const ClassDef * cd)
Definition at line 5069 of file classdef.cpp.
{
  bool allExternals = Config_getBool(ALLEXTERNALS);
  return (allExternals && cd->isLinkable()) || cd->isLinkableInProject();
}
References Config_getBool, ClassDef::isLinkable(), and ClassDef::isLinkableInProject().
Referenced by NestingContext::Private::addClass(), and writeClassTree().
createClassDef()
ClassDefMutable * createClassDef (const QCString & fileName, int startLine, int startColumn, const QCString & name, ClassDef::CompoundType ct, const QCString & ref = QCString(), const QCString & fName = QCString(), bool isSymbol = TRUE, bool isJavaEnum = FALSE)
Factory method to create a new ClassDef object.
Definition at line 363 of file classdef.cpp.
{
  return new ClassDefImpl(fileName,startLine,startColumn,name,ct,ref,fName,isSymbol,isJavaEnum);
}
Referenced by addClassToContext(), createTagLessInstance(), findClassRelation(), findUsedClassesForClass(), and findUsingDeclarations().
createClassDefAlias()
ClassDef * createClassDefAlias (const Definition * newScope, const ClassDef * cd)
Definition at line 555 of file classdef.cpp.
{
  ClassDef *acd = new ClassDefAliasImpl(newScope,cd);
  //printf("cd name=%s localName=%s qualifiedName=%s qualifiedNameWith=%s displayName()=%s\n",
  //    qPrint(acd->name()),qPrint(acd->localName()),qPrint(acd->qualifiedName()),
  //    qPrint(acd->qualifiedNameWithTemplateParameters()),qPrint(acd->displayName()));
  return acd;
}
Referenced by resolveClassNestingRelations().
getClass()
ClassDef * getClass (const QCString & n)
Get a class definition given its name. Returns 0 if the class is not found.
Definition at line 5027 of file classdef.cpp.
{
  if (n.isEmpty()) return 0;
  return Doxygen::classLinkedMap->find(n);
}
References Doxygen::classLinkedMap, LinkedMap< T, Hash, KeyEqual, Map >::find(), and QCString::isEmpty().
Referenced by buildScopeFromQualifiedName(), extractNamespaceName(), findClassWithinClassContext(), findEnumDocumentation(), findEnums(), findInheritedTemplateInstances(), findMember(), findUsedTemplateInstances(), generateClassOrGlobalLink(), generateMemberLink(), MemberDefImpl::getClassDefOfAnonymousType(), getClassMutable(), getScopeDefs(), getTemplateArgumentsFromName(), DocParser::handleLinkedWord(), if(), insertTemplateSpecifierInScope(), MemberDefImpl::isDocumentedFriendClass(), SymbolResolver::resolveClass(), resolveLink(), resolveRef(), setCallContextForVar(), stripTemplateSpecifiersFromScope(), and MemberDefImpl::writeDeclaration().
getClassMutable()
ClassDefMutable * getClassMutable (const QCString & key) inline
Definition at line 481 of file classdef.h.
{
  return toClassDefMutable(getClass(key));
}
References getClass(), and toClassDefMutable().
Referenced by addClassToContext(), addEnumValuesToEnums(), addLocalObjCMethod(), addVariableToFile(), computeClassRelations(), computeTemplateClassRelations(), findClassRelation(), findEnums(), findMember(), findUsingDeclarations(), and findUsingDeclImports().
hasVisibleRoot()
bool hasVisibleRoot (const BaseClassList & bcl)
Definition at line 5033 of file classdef.cpp.
{
  for (const auto &bcd : bcl)
  {
    const ClassDef *cd=bcd.classDef;
    if (cd->isVisibleInHierarchy()) return true;
    if (hasVisibleRoot(cd->baseClasses())) return true;
  }
  return false;
}
References ClassDef::baseClasses(), hasVisibleRoot(), and ClassDef::isVisibleInHierarchy().
Referenced by NestingContext::Private::addClassHierarchy(), DotGfxHierarchyTable::addClassList(), NestingContext::Private::addDerivedClasses(), DotGfxHierarchyTable::addHierarchy(), countClassesInTreeList(), hasVisibleRoot(), writeClassTreeForList(), and writeClassTreeToOutput().
minClassDistance()
int minClassDistance (const ClassDef * cd, const ClassDef * bcd, int level = 0)
Definition at line 5079 of file classdef.cpp.
{
  const int maxInheritanceDepth = 100000;
  if (bcd->categoryOf()) // use class that is being extended in case of
    // an Objective-C category
  {
    bcd=bcd->categoryOf();
  }
  if (cd==bcd) return level;
  if (level==256)
  {
    warn_uncond("class %s seem to have a recursive "
        "inheritance relation!\n",qPrint(cd->name()));
    return -1;
  }
  int m=maxInheritanceDepth;
  for (const auto &bcdi : cd->baseClasses())
  {
    int mc=minClassDistance(bcdi.classDef,bcd,level+1);
    if (mc<m) m=mc;
    if (m<0) break;
  }
  return m;
}
References ClassDef::baseClasses(), ClassDef::categoryOf(), maxInheritanceDepth, minClassDistance(), Definition::name(), qPrint(), and warn_uncond().
Referenced by computeMemberRelations(), getDefsOld(), ClassDefImpl::getMemberByName(), and minClassDistance().
toClassDef() [1/3]
const ClassDef * toClassDef (const Definition * d)
Definition at line 4985 of file classdef.cpp.
{
  if (d && (typeid(*d)==typeid(ClassDefImpl) || typeid(*d)==typeid(ClassDefAliasImpl)))
  {
    return static_cast<const ClassDef*>(d);
  }
  else
  {
    return 0;
  }
}
toClassDef() [2/3]
ClassDef * toClassDef (Definition * d)
Definition at line 4960 of file classdef.cpp.
{
  if (d && (typeid(*d)==typeid(ClassDefImpl) || typeid(*d)==typeid(ClassDefAliasImpl)))
  {
    return static_cast<ClassDef*>(d);
  }
  else
  {
    return 0;
  }
}
Referenced by NestingNodeContext::Private::addClasses(), DocSets::addIndexItem(), ClassDefImpl::addInnerCompound(), NamespaceDefImpl::addInnerCompound(), MemberDefImpl::addListReference(), NestingNodeContext::Private::addMembers(), ClassContext::Private::addTemplateDecls(), NestingNodeContext::Private::createClass(), MemberListInfoContext::Private::createInherited(), definitionToName(), findMemberLink(), SymbolResolver::Private::followPath(), generateClassMemberLink(), generateClassOrGlobalLink(), FTVHelp::Private::generateTree(), ClassDefAliasImpl::getCdAlias(), SymbolResolver::Private::getResolvedSymbol(), SymbolResolver::Private::getResolvedType(), SymbolResolver::Private::getResolvedTypeRec(), ClassDefImpl::getTemplateParameterLists(), SymbolResolver::Private::isAccessibleFrom(), SymbolResolver::Private::isAccessibleFromWithExpScope(), makeQualifiedNameWithTemplateParameters(), MemberDefImpl::moveTo(), scopeIsTemplate(), searchTemplateSpecs(), SearchIndex::setCurrentDoc(), updateCallContextForSmartPointer(), writeDefArgumentList(), writeJavaScriptSearchIndex(), MemberDefImpl::writeMemberDocSimple(), writeObjCMethodCall(), MemberList::writeSimpleDocumentation(), and VhdlDocGen::writeVHDLTypeDocumentation().
toClassDef() [3/3]
ClassDef * toClassDef (DefinitionMutable * d)
Definition at line 4972 of file classdef.cpp.
{
  Definition *d = toDefinition(md);
  if (d && typeid(*d)==typeid(ClassDefImpl))
  {
    return static_cast<ClassDef*>(d);
  }
  else
  {
    return 0;
  }
}
References toDefinition().
toClassDefMutable() [1/2]
ClassDefMutable * toClassDefMutable (const Definition * d)
Definition at line 5009 of file classdef.cpp.
{
  if (d && typeid(*d)==typeid(ClassDefImpl))
  {
    return const_cast<ClassDefMutable*>(static_cast<const ClassDefMutable*>(d));
  }
  else
  {
    return 0;
  }
}
toClassDefMutable() [2/2]
ClassDefMutable * toClassDefMutable (Definition * d)
Definition at line 4997 of file classdef.cpp.
{
  if (d && typeid(*d)==typeid(ClassDefImpl))
  {
    return static_cast<ClassDefMutable*>(d);
  }
  else
  {
    return 0;
  }
}
Referenced by addClassAndNestedClasses(), addClassToContext(), addClassToGroups(), addListReferences(), addMembersToMemberGroup(), ClassDefImpl::addMembersToTemplateInstance(), addMemberToGroups(), ClassDefImpl::addTypeConstraint(), buildCompleteMemberLists(), computeMemberReferences(), computeTemplateClassRelations(), VhdlDocGen::computeVhdlComponentRelations(), ClassDefImpl::countInheritedDecMembers(), countMembers(), createTagLessInstance(), createTemplateInstanceMembers(), distributeClassGroupRelations(), distributeMemberGroupDocumentation(), findClassRelation(), findInheritedTemplateInstances(), findSectionsInDocumentation(), findTagLessClasses(), findTemplateInstanceRelation(), findUsedClassesForClass(), findUsedTemplateInstances(), findUsingDeclarations(), generateClassDocs(), generateClassOrGlobalLink(), generateNamespaceClassDocs(), MemberDef::getClassDefMutable(), getClassMutable(), ClassDefImpl::insertTemplateInstance(), ClassDefImpl::insertUsedFile(), mergeCategories(), ClassDefImpl::mergeCategory(), ClassDefImpl::mergeMembers(), SymbolResolver::resolveClassMutable(), resolveClassNestingRelations(), setAnonymousEnumType(), ClassDefImpl::setGroupDefForAllMembers(), sortMemberLists(), writeClassTree(), MemberDefImpl::writeDeclaration(), MemberList::writeDeclarations(), ClassLinkedRefMap::writeDocumentation(), ClassDefImpl::writeDocumentationForInnerClasses(), ClassDefImpl::writeInheritedMemberDeclarations(), and writeTagFile().