Doxygen: /home/runner/work/doxygen/doxygen/src/index.h File Reference
index.h File Reference
#include "qcstring.h"
Enumerations
enum IndexSections {
isTitlePageStart , isTitlePageAuthor , isMainPage , isModuleIndex ,
isDirIndex , isNamespaceIndex , isConceptIndex , isClassHierarchyIndex ,
isCompoundIndex , isFileIndex , isPageIndex , isModuleDocumentation ,
isDirDocumentation , isNamespaceDocumentation , isClassDocumentation , isConceptDocumentation ,
isFileDocumentation , isExampleDocumentation , isPageDocumentation , isPageDocumentation2 ,
isEndIndex
}
enum HighlightedItem {
HLI_None =0 , HLI_Main , HLI_Modules , HLI_Namespaces ,
HLI_ClassHierarchy , HLI_InterfaceHierarchy , HLI_ExceptionHierarchy , HLI_Classes ,
HLI_Concepts , HLI_Interfaces , HLI_Structs , HLI_Exceptions ,
HLI_AnnotatedClasses , HLI_AnnotatedInterfaces , HLI_AnnotatedStructs , HLI_AnnotatedExceptions ,
HLI_Files , HLI_NamespaceMembers , HLI_Functions , HLI_Globals ,
HLI_Pages , HLI_Examples , HLI_Search , HLI_UserGroup ,
HLI_ClassVisible , HLI_ConceptVisible , HLI_InterfaceVisible , HLI_StructVisible ,
HLI_ExceptionVisible , HLI_NamespaceVisible , HLI_FileVisible
}
enum ClassMemberHighlight {
CMHL_All = 0 , CMHL_Functions , CMHL_Variables , CMHL_Typedefs ,
CMHL_Enums , CMHL_EnumValues , CMHL_Properties , CMHL_Events ,
CMHL_Related , CMHL_Total = CMHL_Related+1
}
enum FileMemberHighlight {
FMHL_All = 0 , FMHL_Functions , FMHL_Variables , FMHL_Typedefs ,
FMHL_Sequences , FMHL_Dictionaries , FMHL_Enums , FMHL_EnumValues ,
FMHL_Defines , FMHL_Total = FMHL_Defines+1
}
enum NamespaceMemberHighlight {
NMHL_All = 0 , NMHL_Functions , NMHL_Variables , NMHL_Typedefs ,
NMHL_Sequences , NMHL_Dictionaries , NMHL_Enums , NMHL_EnumValues ,
NMHL_Total = NMHL_EnumValues+1
}
enum ClassHighlight {
CHL_All = 0 , CHL_Classes , CHL_Structs , CHL_Unions ,
CHL_Interfaces , CHL_Protocols , CHL_Categories , CHL_Exceptions ,
CHL_Total = CHL_Exceptions+1
}
Functions
void writeGraphInfo (OutputList &ol)
void writeIndexHierarchy (OutputList &ol)
void countDataStructures ()
void startTitle (OutputList &ol, const QCString &fileName, const DefinitionMutable *def=0)
void endTitle (OutputList &ol, const QCString &fileName, const QCString &name)
void startFile (OutputList &ol, const QCString &name, const QCString &manName, const QCString &title, HighlightedItem hli=HLI_None, bool additionalIndices=FALSE, const QCString &altSidebarName=QCString())
void endFile (OutputList &ol, bool skipNavIndex=FALSE, bool skipEndContents=FALSE, const QCString &navPath=QCString())
void endFileWithNavPath (const Definition *d, OutputList &ol)
void initClassMemberIndices ()
void initFileMemberIndices ()
void initNamespaceMemberIndices ()
void addClassMemberNameToIndex (const MemberDef *md)
void addFileMemberNameToIndex (const MemberDef *md)
void addNamespaceMemberNameToIndex (const MemberDef *md)
void sortMemberIndexLists ()
QCString fixSpaces (const QCString &s)
int countVisibleMembers (const NamespaceDef *nd)
Variables
int annotatedClasses
int annotatedInterfaces
int annotatedStructs
int annotatedExceptions
int hierarchyClasses
int hierarchyInterfaces
int hierarchyExceptions
int documentedFiles
int documentedGroups
int documentedNamespaces
int documentedConcepts
int indexedPages
int documentedClassMembers [CMHL_Total]
int documentedFileMembers [FMHL_Total]
int documentedNamespaceMembers [NMHL_Total]
int documentedDirs
int documentedPages
Enumeration Type Documentation
ClassHighlight
enum ClassHighlight
Enumerator
CHL_All
CHL_Classes
CHL_Structs
CHL_Unions
CHL_Interfaces
CHL_Protocols
CHL_Categories
CHL_Exceptions
CHL_Total
Definition at line 130 of file index.h.
{
  CHL_All = 0,
  CHL_Classes,
  CHL_Structs,
  CHL_Unions,
  CHL_Interfaces,
  CHL_Protocols,
  CHL_Categories,
  CHL_Exceptions,
  CHL_Total = CHL_Exceptions+1
};
ClassMemberHighlight
enum ClassMemberHighlight
Enumerator
CMHL_All
CMHL_Functions
CMHL_Variables
CMHL_Typedefs
CMHL_Enums
CMHL_EnumValues
CMHL_Properties
CMHL_Events
CMHL_Related
CMHL_Total
Definition at line 89 of file index.h.
{
  CMHL_All = 0,
  CMHL_Functions,
  CMHL_Variables,
  CMHL_Typedefs,
  CMHL_Enums,
  CMHL_EnumValues,
  CMHL_Properties,
  CMHL_Events,
  CMHL_Related,
  CMHL_Total = CMHL_Related+1
};
FileMemberHighlight
enum FileMemberHighlight
Enumerator
FMHL_All
FMHL_Functions
FMHL_Variables
FMHL_Typedefs
FMHL_Sequences
FMHL_Dictionaries
FMHL_Enums
FMHL_EnumValues
FMHL_Defines
FMHL_Total
Definition at line 103 of file index.h.
{
  FMHL_All = 0,
  FMHL_Functions,
  FMHL_Variables,
  FMHL_Typedefs,
  FMHL_Sequences,
  FMHL_Dictionaries,
  FMHL_Enums,
  FMHL_EnumValues,
  FMHL_Defines,
  FMHL_Total = FMHL_Defines+1
};
HighlightedItem
enum HighlightedItem
Enumerator
HLI_None
HLI_Main
HLI_Modules
HLI_Namespaces
HLI_ClassHierarchy
HLI_InterfaceHierarchy
HLI_ExceptionHierarchy
HLI_Classes
HLI_Concepts
HLI_Interfaces
HLI_Structs
HLI_Exceptions
HLI_AnnotatedClasses
HLI_AnnotatedInterfaces
HLI_AnnotatedStructs
HLI_AnnotatedExceptions
HLI_Files
HLI_NamespaceMembers
HLI_Functions
HLI_Globals
HLI_Pages
HLI_Examples
HLI_Search
HLI_UserGroup
HLI_ClassVisible
HLI_ConceptVisible
HLI_InterfaceVisible
HLI_StructVisible
HLI_ExceptionVisible
HLI_NamespaceVisible
HLI_FileVisible
Definition at line 52 of file index.h.
{
  HLI_None=0,
  HLI_Main,
  HLI_Modules,
  //HLI_Directories,
  HLI_Namespaces,
  HLI_ClassHierarchy,
  HLI_InterfaceHierarchy,
  HLI_ExceptionHierarchy,
  HLI_Classes,
  HLI_Concepts,
  HLI_Interfaces,
  HLI_Structs,
  HLI_Exceptions,
  HLI_AnnotatedClasses,
  HLI_AnnotatedInterfaces,
  HLI_AnnotatedStructs,
  HLI_AnnotatedExceptions,
  HLI_Files,
  HLI_NamespaceMembers,
  HLI_Functions,
  HLI_Globals,
  HLI_Pages,
  HLI_Examples,
  HLI_Search,
  HLI_UserGroup,
  HLI_ClassVisible,
  HLI_ConceptVisible,
  HLI_InterfaceVisible,
  HLI_StructVisible,
  HLI_ExceptionVisible,
  HLI_NamespaceVisible,
  HLI_FileVisible
};
IndexSections
enum IndexSections
Enumerator
isTitlePageStart
isTitlePageAuthor
isMainPage
isModuleIndex
isDirIndex
isNamespaceIndex
isConceptIndex
isClassHierarchyIndex
isCompoundIndex
isFileIndex
isPageIndex
isModuleDocumentation
isDirDocumentation
isNamespaceDocumentation
isClassDocumentation
isConceptDocumentation
isFileDocumentation
isExampleDocumentation
isPageDocumentation
isPageDocumentation2
isEndIndex
Definition at line 27 of file index.h.
{
  isTitlePageStart,
  isTitlePageAuthor,
  isMainPage,
  isModuleIndex,
  isDirIndex,
  isNamespaceIndex,
  isConceptIndex,
  isClassHierarchyIndex,
  isCompoundIndex,
  isFileIndex,
  isPageIndex,
  isModuleDocumentation,
  isDirDocumentation,
  isNamespaceDocumentation,
  isClassDocumentation,
  isConceptDocumentation,
  isFileDocumentation,
  isExampleDocumentation,
  isPageDocumentation,
  isPageDocumentation2,
  isEndIndex
};
NamespaceMemberHighlight
enum NamespaceMemberHighlight
Enumerator
NMHL_All
NMHL_Functions
NMHL_Variables
NMHL_Typedefs
NMHL_Sequences
NMHL_Dictionaries
NMHL_Enums
NMHL_EnumValues
NMHL_Total
Definition at line 117 of file index.h.
{
  NMHL_All = 0,
  NMHL_Functions,
  NMHL_Variables,
  NMHL_Typedefs,
  NMHL_Sequences,
  NMHL_Dictionaries,
  NMHL_Enums,
  NMHL_EnumValues,
  NMHL_Total = NMHL_EnumValues+1
};
Function Documentation
addClassMemberNameToIndex()
void addClassMemberNameToIndex (const MemberDef * md)
Definition at line 2666 of file index.cpp.
{
  bool hideFriendCompounds = Config_getBool(HIDE_FRIEND_COMPOUNDS);
  const ClassDef *cd=0;
  if (md->isLinkableInProject() &&
      (cd=md->getClassDef())    &&
      cd->isLinkableInProject() &&
      cd->templateMaster()==0)
  {
    QCString n = md->name();
    int index = getPrefixIndex(n);
    std::string letter = getUTF8CharAt(n.str(),index);
    if (!letter.empty())
    {
      letter = convertUTF8ToLower(letter);
      bool isFriendToHide = hideFriendCompounds &&
        (QCString(md->typeString())=="friend class" ||
         QCString(md->typeString())=="friend struct" ||
         QCString(md->typeString())=="friend union");
      if (!(md->isFriend() && isFriendToHide) &&
          (!md->isEnumValue() || (md->getEnumScope() && !md->getEnumScope()->isStrong()))
         )
      {
        MemberIndexMap_add(g_classIndexLetterUsed[CMHL_All],letter,md);
        documentedClassMembers[CMHL_All]++;
      }
      if (md->isFunction()  || md->isSlot() || md->isSignal())
      {
        MemberIndexMap_add(g_classIndexLetterUsed[CMHL_Functions],letter,md);
        documentedClassMembers[CMHL_Functions]++;
      }
      else if (md->isVariable())
      {
        MemberIndexMap_add(g_classIndexLetterUsed[CMHL_Variables],letter,md);
        documentedClassMembers[CMHL_Variables]++;
      }
      else if (md->isTypedef())
      {
        MemberIndexMap_add(g_classIndexLetterUsed[CMHL_Typedefs],letter,md);
        documentedClassMembers[CMHL_Typedefs]++;
      }
      else if (md->isEnumerate())
      {
        MemberIndexMap_add(g_classIndexLetterUsed[CMHL_Enums],letter,md);
        documentedClassMembers[CMHL_Enums]++;
      }
      else if (md->isEnumValue() && md->getEnumScope() && !md->getEnumScope()->isStrong())
      {
        MemberIndexMap_add(g_classIndexLetterUsed[CMHL_EnumValues],letter,md);
        documentedClassMembers[CMHL_EnumValues]++;
      }
      else if (md->isProperty())
      {
        MemberIndexMap_add(g_classIndexLetterUsed[CMHL_Properties],letter,md);
        documentedClassMembers[CMHL_Properties]++;
      }
      else if (md->isEvent())
      {
        MemberIndexMap_add(g_classIndexLetterUsed[CMHL_Events],letter,md);
        documentedClassMembers[CMHL_Events]++;
      }
      else if (md->isRelated() || md->isForeign() ||
               (md->isFriend() && !isFriendToHide))
      {
        MemberIndexMap_add(g_classIndexLetterUsed[CMHL_Related],letter,md);
        documentedClassMembers[CMHL_Related]++;
      }
    }
  }
}
References CMHL_All, CMHL_Enums, CMHL_EnumValues, CMHL_Events, CMHL_Functions, CMHL_Properties, CMHL_Related, CMHL_Typedefs, CMHL_Variables, Config_getBool, convertUTF8ToLower(), documentedClassMembers, g_classIndexLetterUsed, MemberDef::getClassDef(), MemberDef::getEnumScope(), getPrefixIndex(), getUTF8CharAt(), MemberDef::isEnumerate(), MemberDef::isEnumValue(), MemberDef::isEvent(), MemberDef::isForeign(), MemberDef::isFriend(), MemberDef::isFunction(), ClassDef::isLinkableInProject(), MemberDef::isLinkableInProject(), MemberDef::isProperty(), MemberDef::isRelated(), MemberDef::isSignal(), MemberDef::isSlot(), MemberDef::isStrong(), MemberDef::isTypedef(), MemberDef::isVariable(), MemberIndexMap_add(), Definition::name(), QCString::str(), ClassDef::templateMaster(), and MemberDef::typeString().
Referenced by addMembersToIndex().
addFileMemberNameToIndex()
void addFileMemberNameToIndex (const MemberDef * md)
Definition at line 2818 of file index.cpp.
{
  const FileDef *fd=md->getFileDef();
  if (fd && fd->isLinkableInProject() && md->isLinkableInProject())
  {
    QCString n = md->name();
    int index = getPrefixIndex(n);
    std::string letter = getUTF8CharAt(n.str(),index);
    if (!letter.empty())
    {
      letter = convertUTF8ToLower(letter);
      if (!md->isEnumValue() || (md->getEnumScope() && !md->getEnumScope()->isStrong()))
      {
        MemberIndexMap_add(g_fileIndexLetterUsed[FMHL_All],letter,md);
        documentedFileMembers[FMHL_All]++;
      }
      if (md->isFunction())
      {
        MemberIndexMap_add(g_fileIndexLetterUsed[FMHL_Functions],letter,md);
        documentedFileMembers[FMHL_Functions]++;
      }
      else if (md->isVariable())
      {
        MemberIndexMap_add(g_fileIndexLetterUsed[FMHL_Variables],letter,md);
        documentedFileMembers[FMHL_Variables]++;
      }
      else if (md->isTypedef())
      {
        MemberIndexMap_add(g_fileIndexLetterUsed[FMHL_Typedefs],letter,md);
        documentedFileMembers[FMHL_Typedefs]++;
      }
      else if (md->isSequence())
      {
        MemberIndexMap_add(g_fileIndexLetterUsed[FMHL_Sequences],letter,md);
        documentedFileMembers[FMHL_Sequences]++;
      }
      else if (md->isDictionary())
      {
        MemberIndexMap_add(g_fileIndexLetterUsed[FMHL_Dictionaries],letter,md);
        documentedFileMembers[FMHL_Dictionaries]++;
      }
      else if (md->isEnumerate())
      {
        MemberIndexMap_add(g_fileIndexLetterUsed[FMHL_Enums],letter,md);
        documentedFileMembers[FMHL_Enums]++;
      }
      else if (md->isEnumValue() && md->getEnumScope() && !md->getEnumScope()->isStrong())
      {
        MemberIndexMap_add(g_fileIndexLetterUsed[FMHL_EnumValues],letter,md);
        documentedFileMembers[FMHL_EnumValues]++;
      }
      else if (md->isDefine())
      {
        MemberIndexMap_add(g_fileIndexLetterUsed[FMHL_Defines],letter,md);
        documentedFileMembers[FMHL_Defines]++;
      }
    }
  }
}
References convertUTF8ToLower(), documentedFileMembers, FMHL_All, FMHL_Defines, FMHL_Dictionaries, FMHL_Enums, FMHL_EnumValues, FMHL_Functions, FMHL_Sequences, FMHL_Typedefs, FMHL_Variables, g_fileIndexLetterUsed, MemberDef::getEnumScope(), MemberDef::getFileDef(), getPrefixIndex(), getUTF8CharAt(), MemberDef::isDefine(), MemberDef::isDictionary(), MemberDef::isEnumerate(), MemberDef::isEnumValue(), MemberDef::isFunction(), FileDef::isLinkableInProject(), MemberDef::isLinkableInProject(), MemberDef::isSequence(), MemberDef::isStrong(), MemberDef::isTypedef(), MemberDef::isVariable(), MemberIndexMap_add(), Definition::name(), and QCString::str().
Referenced by addMembersToIndex().
addNamespaceMemberNameToIndex()
void addNamespaceMemberNameToIndex (const MemberDef * md)
Definition at line 2750 of file index.cpp.
{
  const NamespaceDef *nd=md->getNamespaceDef();
  if (nd && nd->isLinkableInProject() && md->isLinkableInProject())
  {
    QCString n = md->name();
    int index = getPrefixIndex(n);
    std::string letter = getUTF8CharAt(n.str(),index);
    if (!letter.empty())
    {
      letter = convertUTF8ToLower(letter);
      if (!md->isEnumValue() || (md->getEnumScope() && !md->getEnumScope()->isStrong()))
      {
        MemberIndexMap_add(g_namespaceIndexLetterUsed[NMHL_All],letter,md);
        documentedNamespaceMembers[NMHL_All]++;
      }
      if (md->isFunction())
      {
        MemberIndexMap_add(g_namespaceIndexLetterUsed[NMHL_Functions],letter,md);
        documentedNamespaceMembers[NMHL_Functions]++;
      }
      else if (md->isVariable())
      {
        MemberIndexMap_add(g_namespaceIndexLetterUsed[NMHL_Variables],letter,md);
        documentedNamespaceMembers[NMHL_Variables]++;
      }
      else if (md->isTypedef())
      {
        MemberIndexMap_add(g_namespaceIndexLetterUsed[NMHL_Typedefs],letter,md);
        documentedNamespaceMembers[NMHL_Typedefs]++;
      }
      else if (md->isSequence())
      {
        MemberIndexMap_add(g_namespaceIndexLetterUsed[NMHL_Sequences],letter,md);
        documentedNamespaceMembers[NMHL_Sequences]++;
      }
      else if (md->isDictionary())
      {
        MemberIndexMap_add(g_namespaceIndexLetterUsed[NMHL_Dictionaries],letter,md);
        documentedNamespaceMembers[NMHL_Dictionaries]++;
      }
      else if (md->isEnumerate())
      {
        MemberIndexMap_add(g_namespaceIndexLetterUsed[NMHL_Enums],letter,md);
        documentedNamespaceMembers[NMHL_Enums]++;
      }
      else if (md->isEnumValue() && md->getEnumScope() && !md->getEnumScope()->isStrong())
      {
        MemberIndexMap_add(g_namespaceIndexLetterUsed[NMHL_EnumValues],letter,md);
        documentedNamespaceMembers[NMHL_EnumValues]++;
      }
    }
  }
}
References convertUTF8ToLower(), documentedNamespaceMembers, g_namespaceIndexLetterUsed, MemberDef::getEnumScope(), MemberDef::getNamespaceDef(), getPrefixIndex(), getUTF8CharAt(), MemberDef::isDictionary(), MemberDef::isEnumerate(), MemberDef::isEnumValue(), MemberDef::isFunction(), MemberDef::isLinkableInProject(), NamespaceDef::isLinkableInProject(), MemberDef::isSequence(), MemberDef::isStrong(), MemberDef::isTypedef(), MemberDef::isVariable(), MemberIndexMap_add(), Definition::name(), NMHL_All, NMHL_Dictionaries, NMHL_Enums, NMHL_EnumValues, NMHL_Functions, NMHL_Sequences, NMHL_Typedefs, NMHL_Variables, and QCString::str().
Referenced by addMembersToIndex().
countDataStructures()
void countDataStructures ()
Definition at line 88 of file index.cpp.
{
  bool sliceOpt = Config_getBool(OPTIMIZE_OUTPUT_SLICE);
  annotatedClasses           = countAnnotatedClasses(&annotatedClassesPrinted, ClassDef::Class); // "classes" + "annotated"
  hierarchyClasses           = countClassHierarchy(ClassDef::Class);     // "hierarchy"
  // "interfaces" + "annotated"
  annotatedInterfaces        = sliceOpt ? countAnnotatedClasses(&annotatedInterfacesPrinted, ClassDef::Interface) : 0;
  // "interfacehierarchy"
  hierarchyInterfaces        = sliceOpt ? countClassHierarchy(ClassDef::Interface) : 0;
  // "structs" + "annotated"
  annotatedStructs           = sliceOpt ? countAnnotatedClasses(&annotatedStructsPrinted, ClassDef::Struct) : 0;
  // "exceptions" + "annotated"
  annotatedExceptions        = sliceOpt ? countAnnotatedClasses(&annotatedExceptionsPrinted, ClassDef::Exception) : 0;
  // "exceptionhierarchy"
  hierarchyExceptions        = sliceOpt ? countClassHierarchy(ClassDef::Exception) : 0;
  countFiles(documentedFiles,documentedFiles);        // "files"
  countRelatedPages(documentedPages,indexedPages);        // "pages"
  documentedGroups           = countGroups();             // "modules"
  documentedNamespaces       = countNamespaces();         // "namespaces"
  documentedConcepts         = countConcepts();           // "concepts"
  documentedDirs             = countDirs();               // "dirs"
  // "globals"
  // "namespacemembers"
  // "functions"
}
References annotatedClasses, annotatedClassesPrinted, annotatedExceptions, annotatedExceptionsPrinted, annotatedInterfaces, annotatedInterfacesPrinted, annotatedStructs, annotatedStructsPrinted, ClassDef::Class, Config_getBool, countAnnotatedClasses(), countClassHierarchy(), countConcepts(), countDirs(), countFiles(), countGroups(), countNamespaces(), countRelatedPages(), documentedConcepts, documentedDirs, documentedFiles, documentedGroups, documentedNamespaces, documentedPages, ClassDef::Exception, hierarchyClasses, hierarchyExceptions, hierarchyInterfaces, indexedPages, ClassDef::Interface, and ClassDef::Struct.
Referenced by parseInput().
countVisibleMembers()
int countVisibleMembers (const NamespaceDef * nd)
Definition at line 1586 of file index.cpp.
{
  int count=0;
  for (const auto &lde : LayoutDocManager::instance().docEntries(LayoutDocManager::Namespace))
  {
    if (lde->kind()==LayoutDocEntry::MemberDef)
    {
      const LayoutDocEntryMemberDef *lmd = dynamic_cast<const LayoutDocEntryMemberDef*>(lde.get());
      if (lmd)
      {
        MemberList *ml = nd->getMemberList(lmd->type);
        if (ml)
        {
          for (const auto &md : *ml)
          {
            if (md->visibleInIndex())
            {
              count++;
            }
          }
        }
      }
    }
  }
  return count;
}
References NamespaceDef::getMemberList(), LayoutDocManager::instance(), LayoutDocEntry::MemberDef, LayoutDocManager::Namespace, and LayoutDocEntryMemberDef::type.
Referenced by NestingContext::Private::addNamespace(), and writeNamespaceTreeElement().
endFile()
void endFile (OutputList & ol, bool skipNavIndex = FALSE, bool skipEndContents = FALSE, const QCString & navPath = QCString())
Definition at line 255 of file index.cpp.
{
  bool generateTreeView = Config_getBool(GENERATE_TREEVIEW);
  ol.pushGeneratorState();
  ol.disableAllBut(OutputGenerator::Html);
  if (!skipNavIndex)
  {
    if (!skipEndContents) ol.endContents();
    if (generateTreeView)
    {
      ol.writeString("</div><!-- doc-content -->\n");
    }
  }
  ol.writeFooter(navPath); // write the footer
  ol.popGeneratorState();
  ol.endFile();
}
References Config_getBool, OutputList::disableAllBut(), OutputList::endContents(), OutputList::endFile(), OutputGenerator::Html, OutputList::popGeneratorState(), OutputList::pushGeneratorState(), OutputList::writeFooter(), and OutputList::writeString().
Referenced by endFileWithNavPath(), generateExampleDocs(), writeAlphabeticalExceptionIndex(), writeAlphabeticalIndex(), writeAlphabeticalInterfaceIndex(), writeAlphabeticalStructIndex(), writeAnnotatedIndexGeneric(), writeClassMemberIndexFiltered(), writeConceptIndex(), GroupDefImpl::writeDocumentation(), PageDefImpl::writeDocumentation(), MemberList::writeDocumentationPage(), writeExampleIndex(), writeFileIndex(), writeFileMemberIndexFiltered(), writeGraphicalClassHierarchy(), writeGraphicalExceptionHierarchy(), writeGraphicalInterfaceHierarchy(), writeGraphInfo(), writeGroupIndex(), writeHierarchicalExceptionIndex(), writeHierarchicalIndex(), writeHierarchicalInterfaceIndex(), writeIndex(), ClassDefImpl::writeMemberList(), writeNamespaceIndex(), writeNamespaceMemberIndexFiltered(), writePageIndex(), and writeUserGroupStubPage().
endFileWithNavPath()
void endFileWithNavPath (const Definition * d, OutputList & ol)
Definition at line 275 of file index.cpp.
{
  bool generateTreeView = Config_getBool(GENERATE_TREEVIEW);
  QCString navPath;
  if (generateTreeView)
  {
    ol.pushGeneratorState();
    ol.disableAllBut(OutputGenerator::Html);
    ol.writeString("</div><!-- doc-content -->\n");
    ol.popGeneratorState();
    navPath = d->navigationPathAsString();
  }
  endFile(ol,generateTreeView,TRUE,navPath);
}
References Config_getBool, OutputList::disableAllBut(), endFile(), OutputGenerator::Html, Definition::navigationPathAsString(), OutputList::popGeneratorState(), OutputList::pushGeneratorState(), TRUE, and OutputList::writeString().
Referenced by ConceptDefImpl::writeDocumentation(), DirDefImpl::writeDocumentation(), DirRelation::writeDocumentation(), FileDefImpl::writeDocumentation(), NamespaceDefImpl::writeDocumentation(), PageDefImpl::writeDocumentation(), ClassDefImpl::writeDocumentation(), MemberList::writeDocumentationPage(), and FileDefImpl::writeSourceFooter().
endTitle()
void endTitle (OutputList & ol, const QCString & fileName, const QCString & name)
Definition at line 229 of file index.cpp.
{
  ol.popGeneratorState();
  ol.endTitleHead(fileName,name);
  ol.endHeaderSection();
}
References OutputList::endHeaderSection(), OutputList::endTitleHead(), and OutputList::popGeneratorState().
Referenced by generateExampleDocs(), writeAlphabeticalExceptionIndex(), writeAlphabeticalIndex(), writeAlphabeticalInterfaceIndex(), writeAlphabeticalStructIndex(), writeAnnotatedIndexGeneric(), writeConceptIndex(), ConceptDefImpl::writeDocumentation(), DirDefImpl::writeDocumentation(), FileDefImpl::writeDocumentation(), NamespaceDefImpl::writeDocumentation(), PageDefImpl::writeDocumentation(), ClassDefImpl::writeDocumentation(), writeExampleIndex(), writeFileIndex(), writeGraphicalClassHierarchy(), writeGraphicalExceptionHierarchy(), writeGraphicalInterfaceHierarchy(), writeGraphInfo(), writeGroupIndex(), writeHierarchicalExceptionIndex(), writeHierarchicalIndex(), writeHierarchicalInterfaceIndex(), ClassDefImpl::writeMemberList(), writeNamespaceIndex(), writePageIndex(), FileDefImpl::writeSourceHeader(), and writeUserGroupStubPage().
fixSpaces()
QCString fixSpaces (const QCString & s)
Definition at line 215 of file index.cpp.
{
  return substitute(s," ","&#160;");
}
References substitute().
Referenced by renderQuickLinksAsTabs(), renderQuickLinksAsTree(), writeClassMemberIndexFiltered(), writeFileMemberIndexFiltered(), writeNamespaceMemberIndexFiltered(), and writeUserGroupStubPage().
initClassMemberIndices()
void initClassMemberIndices ()
Definition at line 2656 of file index.cpp.
{
  int j=0;
  for (j=0;j<CMHL_Total;j++)
  {
    documentedClassMembers[j]=0;
    g_classIndexLetterUsed[j].clear();
  }
}
References CMHL_Total, documentedClassMembers, and g_classIndexLetterUsed.
Referenced by initDoxygen().
initFileMemberIndices()
void initFileMemberIndices ()
Definition at line 2808 of file index.cpp.
{
  int j=0;
  for (j=0;j<NMHL_Total;j++)
  {
    documentedFileMembers[j]=0;
    g_fileIndexLetterUsed[j].clear();
  }
}
References documentedFileMembers, g_fileIndexLetterUsed, and NMHL_Total.
Referenced by initDoxygen().
initNamespaceMemberIndices()
void initNamespaceMemberIndices ()
Definition at line 2740 of file index.cpp.
{
  int j=0;
  for (j=0;j<NMHL_Total;j++)
  {
    documentedNamespaceMembers[j]=0;
    g_namespaceIndexLetterUsed[j].clear();
  }
}
References documentedNamespaceMembers, g_namespaceIndexLetterUsed, and NMHL_Total.
Referenced by initDoxygen().
sortMemberIndexLists()
void sortMemberIndexLists ()
Definition at line 2894 of file index.cpp.
{
  for (auto &idx : g_classIndexLetterUsed)
  {
    sortMemberIndexList(idx);
  }
  for (auto &idx : g_fileIndexLetterUsed)
  {
    sortMemberIndexList(idx);
  }
  for (auto &idx : g_namespaceIndexLetterUsed)
  {
    sortMemberIndexList(idx);
  }
}
References g_classIndexLetterUsed, g_fileIndexLetterUsed, g_namespaceIndexLetterUsed, and sortMemberIndexList().
Referenced by addMembersToIndex().
startFile()
void startFile (OutputList & ol, const QCString & name, const QCString & manName, const QCString & title, HighlightedItem hli = HLI_None, bool additionalIndices = FALSE, const QCString & altSidebarName = QCString())
Definition at line 236 of file index.cpp.
{
  bool disableIndex     = Config_getBool(DISABLE_INDEX);
  ol.startFile(name,manName,title);
  ol.startQuickIndices();
  if (!disableIndex)
  {
    ol.writeQuickLinks(TRUE,hli,name);
  }
  if (!additionalIndices)
  {
    ol.endQuickIndices();
  }
  ol.writeSplitBar(!altSidebarName.isEmpty() ? altSidebarName : name);
  ol.writeSearchInfo();
}
References Config_getBool, OutputList::endQuickIndices(), QCString::isEmpty(), OutputList::startFile(), OutputList::startQuickIndices(), TRUE, OutputList::writeQuickLinks(), OutputList::writeSearchInfo(), and OutputList::writeSplitBar().
Referenced by generateExampleDocs(), writeAlphabeticalExceptionIndex(), writeAlphabeticalIndex(), writeAlphabeticalInterfaceIndex(), writeAlphabeticalStructIndex(), writeAnnotatedIndexGeneric(), writeConceptIndex(), ConceptDefImpl::writeDocumentation(), DirDefImpl::writeDocumentation(), DirRelation::writeDocumentation(), FileDefImpl::writeDocumentation(), GroupDefImpl::writeDocumentation(), NamespaceDefImpl::writeDocumentation(), PageDefImpl::writeDocumentation(), ClassDefImpl::writeDocumentation(), MemberList::writeDocumentationPage(), writeExampleIndex(), writeFileIndex(), writeGraphicalClassHierarchy(), writeGraphicalExceptionHierarchy(), writeGraphicalInterfaceHierarchy(), writeGraphInfo(), writeGroupIndex(), writeHierarchicalExceptionIndex(), writeHierarchicalIndex(), writeHierarchicalInterfaceIndex(), writeIndex(), ClassDefImpl::writeMemberList(), writeNamespaceIndex(), writePageIndex(), FileDefImpl::writeSourceHeader(), and writeUserGroupStubPage().
startTitle()
void startTitle (OutputList & ol, const QCString & fileName, const DefinitionMutable * def = 0)
Definition at line 220 of file index.cpp.
{
  ol.startHeaderSection();
  if (def) def->writeSummaryLinks(ol);
  ol.startTitleHead(fileName);
  ol.pushGeneratorState();
  ol.disable(OutputGenerator::Man);
}
References OutputList::disable(), OutputGenerator::Man, OutputList::pushGeneratorState(), OutputList::startHeaderSection(), OutputList::startTitleHead(), and DefinitionMutable::writeSummaryLinks().
Referenced by generateExampleDocs(), writeAlphabeticalExceptionIndex(), writeAlphabeticalIndex(), writeAlphabeticalInterfaceIndex(), writeAlphabeticalStructIndex(), writeAnnotatedIndexGeneric(), writeConceptIndex(), ConceptDefImpl::writeDocumentation(), DirDefImpl::writeDocumentation(), FileDefImpl::writeDocumentation(), NamespaceDefImpl::writeDocumentation(), PageDefImpl::writeDocumentation(), ClassDefImpl::writeDocumentation(), writeExampleIndex(), writeFileIndex(), writeGraphicalClassHierarchy(), writeGraphicalExceptionHierarchy(), writeGraphicalInterfaceHierarchy(), writeGraphInfo(), writeGroupIndex(), writeHierarchicalExceptionIndex(), writeHierarchicalIndex(), writeHierarchicalInterfaceIndex(), ClassDefImpl::writeMemberList(), writeNamespaceIndex(), writePageIndex(), FileDefImpl::writeSourceHeader(), and writeUserGroupStubPage().
writeGraphInfo()
void writeGraphInfo (OutputList & ol)
Definition at line 3693 of file index.cpp.
{
  if (!Config_getBool(HAVE_DOT) || !Config_getBool(GENERATE_HTML)) return;
  ol.pushGeneratorState();
  ol.disableAllBut(OutputGenerator::Html);
  DotLegendGraph gd;
  gd.writeGraph(Config_getString(HTML_OUTPUT));
  bool oldStripCommentsState = Config_getBool(STRIP_CODE_COMMENTS);
  bool oldCreateSubdirs = Config_getBool(CREATE_SUBDIRS);
  // temporarily disable the stripping of comments for our own code example!
  Config_updateBool(STRIP_CODE_COMMENTS,FALSE);
  // temporarily disable create subdirs for linking to our example
  Config_updateBool(CREATE_SUBDIRS,FALSE);
  startFile(ol,"graph_legend",QCString(),theTranslator->trLegendTitle());
  startTitle(ol,QCString());
  ol.parseText(theTranslator->trLegendTitle());
  endTitle(ol,QCString(),QCString());
  ol.startContents();
  QCString legendDocs = theTranslator->trLegendDocs();
  int s = legendDocs.find("<center>");
  int e = legendDocs.find("</center>");
  QCString imgExt = getDotImageExtension();
  if (imgExt=="svg" && s!=-1 && e!=-1)
  {
    legendDocs = legendDocs.left(s+8) + "
\n" + legendDocs.mid(e);
    //printf("legendDocs=%s\n",qPrint(legendDocs));
  }
  FileDef *fd = createFileDef("","graph_legend.dox");
  ol.generateDoc("graph_legend",1,fd,0,legendDocs,FALSE,FALSE,
                 QCString(),FALSE,FALSE,FALSE);
  delete fd;
  // restore config settings
  Config_updateBool(STRIP_CODE_COMMENTS,oldStripCommentsState);
  Config_updateBool(CREATE_SUBDIRS,oldCreateSubdirs);
  endFile(ol);
  ol.popGeneratorState();
}
References Config_getBool, Config_getString, Config_updateBool, createFileDef(), OutputList::disableAllBut(), endFile(), endTitle(), FALSE, QCString::find(), OutputList::generateDoc(), getDotImageExtension(), OutputGenerator::Html, QCString::left(), QCString::mid(), OutputList::parseText(), OutputList::popGeneratorState(), OutputList::pushGeneratorState(), OutputList::startContents(), startFile(), startTitle(), theTranslator, Translator::trLegendDocs(), Translator::trLegendTitle(), and DotLegendGraph::writeGraph().
Referenced by generateOutput().
writeIndexHierarchy()
void writeIndexHierarchy (OutputList & ol)
Definition at line 5183 of file index.cpp.
{
  writeMenuData();
  LayoutNavEntry *lne = LayoutDocManager::instance().rootNavEntry();
  if (lne)
  {
    writeIndexHierarchyEntries(ol,lne->children());
  }
}
References LayoutNavEntry::children(), LayoutDocManager::instance(), LayoutDocManager::rootNavEntry(), writeIndexHierarchyEntries(), and writeMenuData().
Referenced by generateOutput().
Variable Documentation
annotatedClasses
int annotatedClasses extern
Definition at line 57 of file index.cpp.
Referenced by countDataStructures(), quickLinkVisible(), writeAlphabeticalIndex(), writeAnnotatedIndex(), and writeIndexHierarchyEntries().
annotatedExceptions
int annotatedExceptions extern
Definition at line 65 of file index.cpp.
Referenced by countDataStructures(), quickLinkVisible(), writeAlphabeticalExceptionIndex(), writeAnnotatedExceptionIndex(), and writeIndexHierarchyEntries().
annotatedInterfaces
int annotatedInterfaces extern
Definition at line 60 of file index.cpp.
Referenced by countDataStructures(), quickLinkVisible(), writeAlphabeticalInterfaceIndex(), writeAnnotatedInterfaceIndex(), and writeIndexHierarchyEntries().
annotatedStructs
int annotatedStructs extern
Definition at line 63 of file index.cpp.
Referenced by countDataStructures(), quickLinkVisible(), writeAlphabeticalStructIndex(), writeAnnotatedStructIndex(), and writeIndexHierarchyEntries().
documentedClassMembers
int documentedClassMembers[CMHL_Total] extern
Definition at line 72 of file index.cpp.
Referenced by addClassMemberNameToIndex(), initClassMemberIndices(), quickLinkVisible(), renderQuickLinksAsJs(), writeClassMemberIndex(), and writeClassMemberIndexFiltered().
documentedConcepts
int documentedConcepts extern
Definition at line 70 of file index.cpp.
Referenced by countDataStructures(), quickLinkVisible(), writeConceptIndex(), and writeIndex().
documentedDirs
int documentedDirs extern
Definition at line 77 of file index.cpp.
Referenced by countDataStructures().
documentedFileMembers
int documentedFileMembers[FMHL_Total] extern
Definition at line 73 of file index.cpp.
Referenced by addFileMemberNameToIndex(), initFileMemberIndices(), quickLinkVisible(), renderQuickLinksAsJs(), writeFileMemberIndex(), and writeFileMemberIndexFiltered().
documentedFiles
int documentedFiles extern
Definition at line 75 of file index.cpp.
Referenced by countDataStructures(), generateFileDocs(), quickLinkVisible(), writeFileIndex(), writeIndex(), and writeIndexHierarchyEntries().
documentedGroups
int documentedGroups extern
Definition at line 68 of file index.cpp.
Referenced by countDataStructures(), quickLinkVisible(), writeGroupIndex(), and writeIndex().
documentedNamespaceMembers
int documentedNamespaceMembers[NMHL_Total] extern
Definition at line 74 of file index.cpp.
Referenced by addNamespaceMemberNameToIndex(), initNamespaceMemberIndices(), quickLinkVisible(), renderQuickLinksAsJs(), writeNamespaceMemberIndex(), and writeNamespaceMemberIndexFiltered().
documentedNamespaces
int documentedNamespaces extern
Definition at line 69 of file index.cpp.
Referenced by countDataStructures(), quickLinkVisible(), writeIndex(), writeIndexHierarchyEntries(), and writeNamespaceIndex().
documentedPages
int documentedPages extern
Definition at line 76 of file index.cpp.
Referenced by countDataStructures(), generatePageDocs(), and writeIndex().
hierarchyClasses
int hierarchyClasses extern
Definition at line 59 of file index.cpp.
Referenced by countDataStructures(), quickLinkVisible(), writeGraphicalClassHierarchy(), writeHierarchicalIndex(), and writeIndex().
hierarchyExceptions
int hierarchyExceptions extern
Definition at line 67 of file index.cpp.
Referenced by countDataStructures(), quickLinkVisible(), writeGraphicalExceptionHierarchy(), writeHierarchicalExceptionIndex(), and writeIndex().
hierarchyInterfaces
int hierarchyInterfaces extern
Definition at line 62 of file index.cpp.
Referenced by countDataStructures(), quickLinkVisible(), writeGraphicalInterfaceHierarchy(), writeHierarchicalInterfaceIndex(), and writeIndex().
indexedPages
int indexedPages extern
Definition at line 71 of file index.cpp.
Referenced by countDataStructures(), quickLinkVisible(), and writePageIndex().