Doxygen: /home/runner/work/doxygen/doxygen/src/cppvalue.h File Reference
cppvalue.h File Reference
#include <cstdio>
#include <string>
Classes
class CPPValue
A class representing a C-preprocessor value.
Functions
CPPValue parseOctal (const std::string &token)
CPPValue parseDecimal (const std::string &token)
CPPValue parseHexadecimal (const std::string &token)
CPPValue parseBinary (const std::string &token)
CPPValue parseCharacter (const std::string &token)
CPPValue parseFloat (const std::string &token)
Function Documentation
parseBinary()
CPPValue parseBinary (const std::string & token)
Definition at line 54 of file cppvalue.cpp.
{
  long val = 0;
  for (const char *p = token.c_str(); *p != 0; p++)
  {
    if (*p >= '0' && *p <= '1') val = val * 2 + *p - '0';
  }
  return CPPValue(val);
}
parseCharacter()
CPPValue parseCharacter (const std::string & token)
Definition at line 64 of file cppvalue.cpp.
{
  if (token[1]=='\\')
  {
    switch(token[2])
    {
      case 'n':  return CPPValue('\n');
      case 't':  return CPPValue('\t');
      case 'v':  return CPPValue('\v');
      case 'b':  return CPPValue('\b');
      case 'r':  return CPPValue('\r');
      case 'f':  return CPPValue('\f');
      case 'a':  return CPPValue('\a');
      case '\\': return CPPValue('\\');
      case '?':  return CPPValue('\?');
      case '\'': return CPPValue('\'');
      case '"':  return CPPValue('"');
      case '0':  // fall through
      case '1':  // fall through
      case '2':  // fall through
      case '3':  // fall through
      case '4':  // fall through
      case '5':  // fall through
      case '6':  // fall through
      case '7':  // fall through
                 return parseOctal(token);
      case 'x':
      case 'X':  return parseHexadecimal(token);
      default:   printf("Invalid escape sequence %s found!\n",token.c_str());
                 return CPPValue(0L);
    }
  }
  return CPPValue(token[1]);
}
References parseHexadecimal(), and parseOctal().
parseDecimal()
CPPValue parseDecimal (const std::string & token)
Definition at line 31 of file cppvalue.cpp.
{
  long val = 0;
  for (const char *p = token.c_str(); *p != 0; p++)
  {
    if (*p >= '0' && *p <= '9') val = val * 10 + *p - '0';
  }
  return CPPValue(val);
}
parseFloat()
CPPValue parseFloat (const std::string & token)
Definition at line 99 of file cppvalue.cpp.
{
  return CPPValue(std::stod(token));
}
parseHexadecimal()
CPPValue parseHexadecimal (const std::string & token)
Definition at line 41 of file cppvalue.cpp.
{
  long val = 0;
  for (const char *p = token.c_str(); *p != 0; p++)
  {
    if      (*p >= '0' && *p <= '9') val = val * 16 + *p - '0';
    else if (*p >= 'a' && *p <= 'f') val = val * 16 + *p - 'a' + 10;
    else if (*p >= 'A' && *p <= 'F') val = val * 16 + *p - 'A' + 10;
  }
  //printf("parseHexadecimal %s->%x\n",qPrint(token),val);
  return CPPValue(val);
}
Referenced by parseCharacter().
parseOctal()
CPPValue parseOctal (const std::string & token)
Definition at line 21 of file cppvalue.cpp.
{
  long val = 0;
  for (const char *p = token.c_str(); *p != 0; p++)
  {
    if (*p >= '0' && *p <= '7') val = val * 8 + *p - '0';
  }
  return CPPValue(val);
}
Referenced by parseCharacter().