Doxygen: Trace Namespace Reference
Trace Namespace Reference
Functions
QCString trunc (const QCString &s, size_t numChars=15)
Function Documentation
trunc()
QCString Trace::trunc (const QCString & s, size_t numChars = 15) inline
Definition at line 44 of file trace.h.
  {
    QCString result;
    size_t i=0;
    for (; i<numChars && i<s.length(); i++)
    {
      char c=s.at(i);
      if      (c=='\n') { result+="\\n"; }
      else if (c=='\t') { result+="\\t"; }
      else if (c=='\r') { result+="\\r"; }
      else if (c=='\\') { result+="\\\\"; }
      else result+=c;
    }
    if (i<s.length()) result+="...";
    return result;
  }
References QCString::at(), QCString::length(), and numChars.
Referenced by addClassToContext(), Markdown::addStrEscapeUtf8Nbsp(), computeIndentExcludingListMarkers(), escapeDoubleQuotes(), escapeSpecialChars(), Markdown::extractPageTitle(), Markdown::extractTitleId(), Markdown::findEmphasisChar(), Markdown::findEndOfLine(), findTableColumns(), ExpressionParser::getNextToken(), handleCommentBlock(), handleParametersCommentBlocks(), hasLineBreak(), Markdown::isAtxHeader(), Markdown::isBlockCommand(), isBlockQuote(), isCodeBlock(), isEmptyLine(), isEndOfList(), isExplicitPage(), isFencedCodeBlock(), Markdown::isHeaderline(), isHRuler(), isLinkRef(), isListMarker(), Markdown::isSpecialCommand(), isTableBlock(), DocInclude::parse(), DocIncOperator::parse(), TemplateParser::parse(), CommentScanner::parseCommentBlock(), parseCompounds(), ExpressionParser::parseExpression(), parsePrototype(), Markdown::processBlocks(), Markdown::processCodeSpan(), DocParser::processCopyDoc(), Markdown::processEmphasis(), Markdown::processEmphasis1(), Markdown::processEmphasis2(), Markdown::processEmphasis3(), Markdown::processHtmlTag(), Markdown::processHtmlTagWrite(), Markdown::processInline(), Markdown::processLink(), Markdown::processNmdash(), Markdown::processQuotations(), Markdown::processQuoted(), Markdown::processSpecialCommand(), TemplateNodeBlock::TemplateNodeBlock(), TemplateNodeCloseSubIndex::TemplateNodeCloseSubIndex(), TemplateNodeCreate::TemplateNodeCreate(), TemplateNodeCycle::TemplateNodeCycle(), TemplateNodeEncoding::TemplateNodeEncoding(), TemplateNodeExtend::TemplateNodeExtend(), TemplateNodeFor::TemplateNodeFor(), TemplateNodeIf::TemplateNodeIf(), TemplateNodeInclude::TemplateNodeInclude(), TemplateNodeIndexEntry::TemplateNodeIndexEntry(), TemplateNodeMarkers::TemplateNodeMarkers(), TemplateNodeOpenSubIndex::TemplateNodeOpenSubIndex(), TemplateNodeRange::TemplateNodeRange(), TemplateNodeRepeat::TemplateNodeRepeat(), TemplateNodeResource::TemplateNodeResource(), TemplateNodeSet::TemplateNodeSet(), TemplateNodeText::TemplateNodeText(), TemplateNodeTree::TemplateNodeTree(), TemplateNodeWith::TemplateNodeWith(), Markdown::writeBlockQuote(), Markdown::writeCodeBlock(), Markdown::writeFencedCodeBlock(), Markdown::writeMarkdownImage(), Markdown::writeOneLineHeaderOrRuler(), and Markdown::writeTableBlock().