Doxygen: /home/runner/work/doxygen/doxygen/src/formula.cpp File Reference
formula.cpp File Reference
#include "formula.h"
#include "message.h"
#include "config.h"
#include "util.h"
#include "portable.h"
#include "image.h"
#include "fileinfo.h"
#include "dir.h"
#include "regex.h"
#include "linkedmap.h"
#include <map>
#include <vector>
#include <string>
#include <utility>
#include <fstream>
#include "doxygen.h"
#include "indexlist.h"
Classes
struct FormulaManager::Private
Macros
#define RM_TMP_FILES (true)
Functions
static int determineInkscapeVersion (Dir &thisDir)
static bool createDVIFile (const QCString &fileName)
static bool createPostscriptFile (const QCString &fileName, const QCString &formBase, int pageIndex)
static bool createEPSbboxFile (const QCString &formBase)
static bool extractBoundingBox (const QCString &formBase, int *x1, int *y1, int *x2, int *y2, double *x1hi, double *y1hi, double *x2hi, double *y2hi)
static bool createCroppedPDF (const QCString &formBase, int x1, int y1, int x2, int y2)
static bool createCroppedEPS (const QCString &formBase)
static bool createSVGFromPDF (const QCString &formBase, const QCString &outFile)
static bool createSVGFromPDFviaInkscape (Dir &thisDir, const QCString &formBase, const QCString &outFile)
static bool updateEPSBoundingBox (const QCString &formBase, int x1, int y1, int x2, int y2, double x1hi, double y1hi, double x2hi, double y2hi)
static bool createPNG (const QCString &formBase, const QCString &outFile, double scaleFactor)
Macro Definition Documentation
RM_TMP_FILES
#define RM_TMP_FILES (true)
Definition at line 40 of file formula.cpp.
Function Documentation
createCroppedEPS()
static bool createCroppedEPS (const QCString & formBase) static
Definition at line 379 of file formula.cpp.
{
  char args[4096];
  // crop the image to its bounding box
  sprintf(args,"-q -dBATCH -dNOPAUSE -P- -dNOSAFER -sDEVICE=eps2write"
              " -o %s_tmp.eps -f %s_tmp.ps",qPrint(formBase),qPrint(formBase));
  Portable::sysTimerStart();
  if (Portable::system(Portable::ghostScriptCommand(),args)!=0)
  {
    err("Problems running %s. Check your installation!\n",Portable::ghostScriptCommand());
    Portable::sysTimerStop();
    return false;
  }
  return true;
}
References err(), Portable::ghostScriptCommand(), qPrint(), Portable::system(), Portable::sysTimerStart(), and Portable::sysTimerStop().
Referenced by FormulaManager::createFormulasTexFile().
createCroppedPDF()
static bool createCroppedPDF (const QCString & formBase, int x1, int y1, int x2, int y2) static
Definition at line 361 of file formula.cpp.
{
  char args[4096];
  // crop the image to its bounding box
  sprintf(args,"-q -dBATCH -dNOPAUSE -P- -dNOSAFER -sDEVICE=pdfwrite"
              " -o %s_tmp.pdf -c \"[/CropBox [%d %d %d %d] /PAGES pdfmark\" -f %s_tmp.ps",
      qPrint(formBase),x1,y1,x2,y2,qPrint(formBase));
  Portable::sysTimerStart();
  if (Portable::system(Portable::ghostScriptCommand(),args)!=0)
  {
    err("Problems running %s. Check your installation!\n",Portable::ghostScriptCommand());
    Portable::sysTimerStop();
    return false;
  }
  Portable::sysTimerStop();
  return true;
}
References err(), Portable::ghostScriptCommand(), qPrint(), Portable::system(), Portable::sysTimerStart(), and Portable::sysTimerStop().
Referenced by FormulaManager::createFormulasTexFile().
createDVIFile()
static bool createDVIFile (const QCString & fileName) static
Definition at line 247 of file formula.cpp.
{
  QCString latexCmd = "latex";
  char args[4096];
  Portable::sysTimerStart();
  int rerunCount=1;
  while (rerunCount<8)
  {
    //printf("Running latex...\n");
    sprintf(args,"-interaction=batchmode %s >%s",qPrint(fileName),Portable::devNull());
    if ((Portable::system(latexCmd,args)!=0) || (Portable::system(latexCmd,args)!=0))
    {
      err("Problems running latex. Check your installation or look "
          "for typos in %s.tex and check %s.log!\n",qPrint(fileName),qPrint(fileName));
      Portable::sysTimerStop();
      return false;
    }
    // check the log file if we need to run latex again to resolve references
    QCString logFile = fileToString(fileName+".log");
    if (logFile.isEmpty() ||
        (logFile.find("Rerun to get cross-references right")==-1 && logFile.find("Rerun LaTeX")==-1))
    {
      break;
    }
    rerunCount++;
  }
  Portable::sysTimerStop();
  return true;
}
References Portable::devNull(), err(), fileToString(), QCString::find(), QCString::isEmpty(), qPrint(), Portable::system(), Portable::sysTimerStart(), and Portable::sysTimerStop().
Referenced by FormulaManager::createFormulasTexFile().
createEPSbboxFile()
static bool createEPSbboxFile (const QCString & formBase) static
Definition at line 294 of file formula.cpp.
{
  char args[4096];
  // extract the bounding box for the postscript file
  sprintf(args,"-q -dBATCH -dNOPAUSE -P- -dNOSAFER -sDEVICE=bbox %s_tmp.ps 2>%s_tmp.epsi",
      qPrint(formBase),qPrint(formBase));
  Portable::sysTimerStart();
  if (Portable::system(Portable::ghostScriptCommand(),args)!=0)
  {
    err("Problems running %s. Check your installation!\n",Portable::ghostScriptCommand());
    Portable::sysTimerStop();
    return false;
  }
  Portable::sysTimerStop();
  return true;
}
References err(), Portable::ghostScriptCommand(), qPrint(), Portable::system(), Portable::sysTimerStart(), and Portable::sysTimerStop().
Referenced by FormulaManager::createFormulasTexFile().
createPNG()
static bool createPNG (const QCString & formBase, const QCString & outFile, double scaleFactor) static
Definition at line 477 of file formula.cpp.
{
  char args[4096];
  Portable::sysTimerStop();
  sprintf(args,"-q -dNOSAFER -dBATCH -dNOPAUSE -dEPSCrop -sDEVICE=pnggray -dGraphicsAlphaBits=4 -dTextAlphaBits=4 "
               "-r%d -sOutputFile=%s %s_tmp_corr.eps",static_cast<int>(scaleFactor*72),qPrint(outFile),qPrint(formBase));
  Portable::sysTimerStart();
  if (Portable::system(Portable::ghostScriptCommand(),args)!=0)
  {
    err("Problems running %s. Check your installation!\n",Portable::ghostScriptCommand());
    Portable::sysTimerStop();
    return false;
  }
  Portable::sysTimerStop();
  return true;
}
References err(), Portable::ghostScriptCommand(), qPrint(), Portable::system(), Portable::sysTimerStart(), and Portable::sysTimerStop().
Referenced by FormulaManager::createFormulasTexFile().
createPostscriptFile()
static bool createPostscriptFile (const QCString & fileName, const QCString & formBase, int pageIndex) static
Definition at line 277 of file formula.cpp.
{
  char args[4096];
  // run dvips to convert the page with number pageIndex to an
  // postscript file.
  sprintf(args,"-q -D 600 -n 1 -p %d -o %s_tmp.ps %s.dvi",pageIndex,qPrint(formBase),qPrint(fileName));
  Portable::sysTimerStart();
  if (Portable::system("dvips",args)!=0)
  {
    err("Problems running dvips. Check your installation!\n");
    Portable::sysTimerStop();
    return false;
  }
  Portable::sysTimerStop();
  return true;
}
References err(), qPrint(), Portable::system(), Portable::sysTimerStart(), and Portable::sysTimerStop().
Referenced by FormulaManager::createFormulasTexFile().
createSVGFromPDF()
static bool createSVGFromPDF (const QCString & formBase, const QCString & outFile) static
Definition at line 395 of file formula.cpp.
{
  char args[4096];
  sprintf(args,"%s_tmp.pdf %s",qPrint(formBase),qPrint(outFile));
  Portable::sysTimerStart();
  if (Portable::system("pdf2svg",args)!=0)
  {
    err("Problems running pdf2svg. Check your installation!\n");
    Portable::sysTimerStop();
    return false;
  }
  Portable::sysTimerStop();
  return true;
}
References err(), qPrint(), Portable::system(), Portable::sysTimerStart(), and Portable::sysTimerStop().
Referenced by FormulaManager::createFormulasTexFile().
createSVGFromPDFviaInkscape()
static bool createSVGFromPDFviaInkscape (Dir & thisDir, const QCString & formBase, const QCString & outFile) static
Definition at line 410 of file formula.cpp.
{
  char args[4096];
  int inkscapeVersion = determineInkscapeVersion(thisDir);
  if (inkscapeVersion == -1)
  {
    err("Problems determining the version of inkscape. Check your installation!\n");
    return false;
  }
  else if (inkscapeVersion == 0)
  {
    sprintf(args,"-l %s -z %s_tmp.pdf 2>%s",qPrint(outFile),qPrint(formBase),Portable::devNull());
  }
  else // inkscapeVersion >= 1
  {
    sprintf(args,"--export-type=svg --export-filename=%s %s_tmp.pdf 2>%s",qPrint(outFile),qPrint(formBase),Portable::devNull());
  }
  Portable::sysTimerStart();
  if (Portable::system("inkscape",args)!=0)
  {
    err("Problems running inkscape. Check your installation!\n");
    Portable::sysTimerStop();
    return false;
  }
  Portable::sysTimerStop();
  return true;
}
References determineInkscapeVersion(), Portable::devNull(), err(), qPrint(), Portable::system(), Portable::sysTimerStart(), and Portable::sysTimerStop().
Referenced by FormulaManager::createFormulasTexFile().
determineInkscapeVersion()
static int determineInkscapeVersion (Dir & thisDir) static
Definition at line 689 of file formula.cpp.
{
  // The command line interface (CLI) of Inkscape 1.0 has changed in comparison to
  // previous versions. In order to invokine Inkscape, the used version is detected
  // and based on the version the right syntax of the CLI is chosen.
  static int inkscapeVersion = -2;
  if (inkscapeVersion == -2) // initial one time version check
  {
    QCString inkscapeVersionFile = "inkscape_version" ;
    inkscapeVersion = -1;
    QCString args = "-z --version >"+inkscapeVersionFile+" 2>"+Portable::devNull();
    Portable::sysTimerStart();
    if (Portable::system("inkscape",args)!=0)
    {
      // looks like the old syntax gave problems, lets try the new syntax
      args = " --version >"+inkscapeVersionFile+" 2>"+Portable::devNull();
      if (Portable::system("inkscape",args)!=0)
      {
        Portable::sysTimerStop();
        return -1;
      }
    }
    // read version file and determine major version
    std::ifstream inkscapeVersionIn(inkscapeVersionFile.str(),std::ifstream::in);
    if (inkscapeVersionIn.is_open())
    {
      std::string line;
      while (getline(inkscapeVersionIn,line))
      {
        size_t dotPos = line.find('.');
        if (line.rfind("Inkscape ",0)==0 && dotPos>0)
        {
          // get major version
          inkscapeVersion = std::stoi(line.substr(9,dotPos-9));
          break;
        }
      }
      inkscapeVersionIn.close();
    }
    else // failed to open version file
    {
      Portable::sysTimerStop();
      return -1;
    }
    if (RM_TMP_FILES)
    {
      thisDir.remove(inkscapeVersionFile.str());
    }
    Portable::sysTimerStop();
  }
  return inkscapeVersion;
}
References Portable::devNull(), Dir::remove(), RM_TMP_FILES, QCString::str(), Portable::system(), Portable::sysTimerStart(), and Portable::sysTimerStop().
Referenced by createSVGFromPDFviaInkscape().
extractBoundingBox()
static bool extractBoundingBox (const QCString & formBase, int * x1, int * y1, int * x2, int * y2, double * x1hi, double * y1hi, double * x2hi, double * y2hi) static
Definition at line 311 of file formula.cpp.
{
  FileInfo fi((formBase+"_tmp.epsi").str());
  if (fi.exists())
  {
    QCString eps = fileToString(formBase+"_tmp.epsi");
    int i = eps.find("%%BoundingBox:");
    if (i!=-1)
    {
      sscanf(eps.data()+i,"%%%%BoundingBox:%d %d %d %d",x1,y1,x2,y2);
    }
    else
    {
      err("Couldn't extract bounding box from %s_tmp.epsi",qPrint(formBase));
      return false;
    }
    i = eps.find("%%HiResBoundingBox:");
    if (i!=-1)
    {
      sscanf(eps.data()+i,"%%%%HiResBoundingBox:%lf %lf %lf %lf",x1hi,y1hi,x2hi,y2hi);
    }
    else
    {
      err("Couldn't extract high resolution bounding box from %s_tmp.epsi",qPrint(formBase));
      return false;
    }
  }
  //printf("Bounding box [%d %d %d %d]\n",x1,y1,x2,y2);
  return true;
}
References QCString::data(), err(), FileInfo::exists(), fileToString(), QCString::find(), and qPrint().
Referenced by FormulaManager::createFormulasTexFile().
updateEPSBoundingBox()
static bool updateEPSBoundingBox (const QCString & formBase, int x1, int y1, int x2, int y2, double x1hi, double y1hi, double x2hi, double y2hi) static
Definition at line 439 of file formula.cpp.
{
  // read back %s_tmp.eps and replace
  // bounding box values with x1,y1,x2,y2 and remove the HiResBoundingBox
  std::ifstream epsIn(formBase.str()+"_tmp.eps",std::ifstream::in);
  std::ofstream epsOut(formBase.str()+"_tmp_corr.eps",std::ofstream::out | std::ofstream::binary);
  if (epsIn.is_open() && epsOut.is_open())
  {
    std::string line;
    while (getline(epsIn,line))
    {
      if (line.rfind("%%BoundingBox",0)==0)
      {
        epsOut << "%%BoundingBox: " << x1 << " " << y1 << " " << x2 << " " << y2 << "\n";
      }
      else if (line.rfind("%%HiResBoundingBox",0)==0)
      {
        epsOut << "%%HiResBoundingBox: " << x1hi << " " << y1hi << " " << x2hi << " " << y2hi << "\n";
      }
      else
      {
        epsOut << line << "\n";
      }
    }
    epsIn.close();
    epsOut.close();
  }
  else
  {
    err("Problems correcting the eps files from %s_tmp.eps to %s_tmp_corr.eps\n",
        qPrint(formBase),qPrint(formBase));
    return false;
  }
  return true;
}
References err(), qPrint(), and QCString::str().
Referenced by FormulaManager::createFormulasTexFile().