Doxygen: DocHtmlDetails Class Reference
DocHtmlDetails Class Reference
Node Html details.
#include <docnode.h>
Public Member Functions
DocHtmlDetails (DocParser *parser, DocNodeVariant *parent, const HtmlAttribList &attribs)
const HtmlAttribList & attribs () const
int parse (DocNodeVariant *)
Public Member Functions inherited from DocCompoundNode
DocCompoundNode (DocParser *parser, DocNodeVariant *parent)
DocNodeList & children ()
const DocNodeList & children () const
Public Member Functions inherited from DocNode
DocNode (DocParser *parser, DocNodeVariant *parent)
DocNode (const DocNode &)=delete
DocNode & operator= (const DocNode &)=delete
DocNode (DocNode &&)=default
DocNode & operator= (DocNode &&)=default
~DocNode ()=default
DocNodeVariant * parent ()
const DocNodeVariant * parent () const
DocParser * parser ()
const DocParser * parser () const
void setParent (DocNodeVariant *parent)
bool isPreformatted () const
Private Attributes
HtmlAttribList m_attribs
Additional Inherited Members
Protected Types inherited from DocNode
enum RefType { Unknown , Anchor , Section , Table }
Protected Member Functions inherited from DocNode
void setInsidePreformatted (bool p)
Detailed Description
Node Html details.
Definition at line 797 of file docnode.h.
Constructor & Destructor Documentation
DocHtmlDetails()
DocHtmlDetails::DocHtmlDetails (DocParser * parser, DocNodeVariant * parent, const HtmlAttribList & attribs) inline
Definition at line 800 of file docnode.h.
                                                                                           :
       DocCompoundNode(parser,parent), m_attribs(attribs) {}
Member Function Documentation
attribs()
const HtmlAttribList & DocHtmlDetails::attribs () const inline
Definition at line 802 of file docnode.h.
{ return m_attribs; }
References m_attribs.
Referenced by HtmlDocVisitor::operator()().
parse()
int DocHtmlDetails::parse (DocNodeVariant * thisVariant)
Definition at line 1289 of file docnode.cpp.
{
  DBG(("DocHtmlHtmlDetails::parse() start\n"));
  int retval=0;
  auto ns = AutoNodeStack(parser(),thisVariant);
  // parse one or more paragraphs
  bool isFirst=TRUE;
  DocPara *par=0;
  do
  {
    auto vDocPara = children().append<DocPara>(parser(),thisVariant);
    par = children().get_last<DocPara>();
    if (isFirst) { par->markFirst(); isFirst=FALSE; }
    retval=par->parse(vDocPara);
  }
  while (retval==TK_NEWPARA);
  if (par) par->markLast();
  DBG(("DocHtmlHtmlDetails::parse() end retval=%s\n",DocTokenizer::retvalToString(retval)));
  return (retval==RetVal_EndHtmlDetails) ? RetVal_OK : retval;
}
References DocNodeList::append(), DocCompoundNode::children(), DBG, FALSE, DocNodeList::get_last(), DocPara::markFirst(), DocPara::markLast(), DocPara::parse(), DocNode::parser(), RetVal_EndHtmlDetails, RetVal_OK, DocTokenizer::retvalToString(), TK_NEWPARA, and TRUE.
Member Data Documentation
m_attribs
HtmlAttribList DocHtmlDetails::m_attribs private
Definition at line 806 of file docnode.h.
Referenced by attribs().
The documentation for this class was generated from the following files:
/home/runner/work/doxygen/doxygen/src/docnode.h
/home/runner/work/doxygen/doxygen/src/docnode.cpp